camel-ai/camel

- camel/messages/base.py
- test/messages/test_message_base.py
As discussed, the `__getattribute__` method may make `BaseMessage` too complicated. So we decide to remove it.
> Remove `__getattribute__` from `BaseMessage`

- camel/agents/chat_agent.py
- camel/agents/critic_agent.py
- camel/agents/role_playing.py
- camel/messages/chat_messages.py
- examples/code/role_playing_multiprocess.py
Made setting user role at backend the responsibility of Agent step
A developer using agents has to keep track of the role flag of the messages fed to agent.step() which may be flexible but error-prone.
> Moved all set_user_role_at_backend into Agent step

- examples/code/role_playing.py
- examples/test/test_code_example.py
Add an example of using `RolePlaying` for `Code` task.
> `Code` `RolePlaying` example

- camel/agents/chat_agent.py
- test/agents/test_chat_agent.py
Have discussed with @lightaime and decided only to keep an "original"("initial") system message which will be used for adding language-setting prompt. This will make the system message's length fixed even after multiple `set_output_language` operations are done. The corresponding test is added in `test_chat_agent.py`
close #215
> Fix set_output_language

- camel/agents/embodied_agent.py
- camel/agents/tool_agents/hugging_face_tool_agent.py
- pyproject.toml
- test/agents/test_embodied_agent.py
- test/agents/tool_agents/test_hugging_face_tool_agent.py
The hugging face `transformers` package has updated to v4.31.0. They introduced a new wrapping type of `PIL.Image` called `AgentImage` as the return value of their agent, which causing test errors in `test/agents/tool_agents/test_hugging_face_tool_agent.py`. This PR fixes it.
@camel-ai/camel-intern-team If this PR is merged, please upgrade your local dependency `transformers=4.31.0` to avoid local test errors.
> Fix huggingface test error

- camel/societies/role_playing.py
- examples/ai_society/role_playing.py
- examples/ai_society/role_playing_multi_lingual.py
- examples/code/role_playing.py
- test/agents/test_role_playing.py
Remove "global" `model_type` from the `RolePlaying`.
User can specify `model` in each `*agent_kwargs` instead, which is more flexible. Especially if user want to use different models for different agents during role playing.
This PR includes:
- Modification of `RolePlaying`
- Add / modify corresponding unit tests to `test/agents/test_role_playing.py`
- Modify current examples
Fixes #190
> Remove `model_type` from the `RolePlaying`

- .github/workflows/documentation.yaml
- .github/workflows/pytest_apps.yml
- .github/workflows/pytest_package.yml
Fix master branch test fail.
The caching environment prevent the pr branch from pytest fail. So I change the caching logic. However, it seems to be useless to cache the env without `poetry.lock`. How about just remove caching?
> Fix master test fail

- camel/configs.py
- camel/societies/role_playing.py
- examples/function_call/role_playing_with_function.py
Remove `assistant_funtions` from `RolePlaying` to simplify the RolePlaying API and fix a bug: https://github.com/camel-ai/camel/issues/248
> Remove `assistant_funtions` from `RolePlaying`

- test/agents/test_role_playing.py
- test/functions/test_search_functions.py
This testcase can detect #248.
Also add test coverage for `RolePlaying.init_chat()`
> Add roleplaying test

- test/functions/test_search_functions.py
Modified the test `tests_search_wiki_with_ambiguity` by directly setting `expected_output` to be the summary of entity `New York (state)`. By doing this, this test can test whether the function does find the correct term and accurately check the summary content.
close #260 
> Modified search wiki test

- camel/configs.py
- camel/functions/search_functions.py
- camel/societies/role_playing.py
- examples/function_call/role_playing_with_function.py
- pyproject.toml
- test/agents/test_role_playing.py
- test/functions/test_search_functions.py
> Update the branch feature/role-generation from master

- camel/agents/chat_agent.py
- camel/embeddings/__init__.py
- camel/embeddings/base.py
- camel/embeddings/openai_embedding.py
- camel/models/openai_model.py
- camel/types/__init__.py
- camel/types/enums.py
- camel/utils/commons.py
- test/embeddings/test_openai_embedding.py
This PR add text embedding support, including a base embedding abstract class and OpenAI embedding APIs.
> feat(embeddings): Add text embedding feature

- camel/types/enums.py
Fix typo in `value_for_tiktoken`
> Fix typo in `value_for_tiktoken`

- camel/prompts/base.py
- camel/utils/python_interpreter.py
- docs/get_started/code_prompt.md
- test/prompts/test_prompt_base.py
- test/utils/test_python_interpreter.py
Fix default action space bug in `CodePrompt`
> Fix default action space bug in `CodePrompt`

- camel/models/model_factory.py
Add a if judgement at the end of model_factory.py. If the model type is open source model, do not pass api_key to the initialization. Otherwise, pass api_key to the initialization since I find out that recently, all other models' initialization contains api key.
close #645 
> fix: Resolve Open Source Model Initialization in model_factory.py

- camel/types/enums.py
- test/models/test_azure_openai_model.py
- test/models/test_litellm_model.py
- test/models/test_ollama_model.py
- test/models/test_openai_model.py
- test/models/test_vllm_model.py
OpenAI does not support gpt-4-32k model anymore.
error:
``` bash
raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4-32k` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
```
refer to:
https://platform.openai.com/docs/models
> fix: remove gpt-4-32k model

- camel/retrievers/auto_retriever.py
- camel/retrievers/vector_retriever.py
- test/retrievers/test_auto_retriever.py
Auto retrieval support Element as input
```
uio = UnstructuredIO()
test_element = uio.create_element_from_text(
text="""Introducing 🦀 CRAB: Cross-environment Agent Benchmark for 
Multimodal Language Model Agents
🦀 CRAB provides an end-to-end and easy-to-use framework to build 
multimodal agents, operate environments, and create benchmarks to evaluate 
them, featuring three key components:
- 🔀 Cross-environment support - agents can operate tasks in 📱 Android 
and 💻 Ubuntu.
- 🕸️ Graph evaluator - provides a fine-grain evaluation metric for agents.
- 🤖 Task generation - composes subtasks to automatically generate tasks.
By connecting all devices to agents, 🦀CRAB unlocks greater capabilities 
for human-like tasks than ever before.
Use 🦀 CRAB to benchmark your multimodal agents! """, …
```
> feat: Auto retrieval support Element as input

- camel/retrievers/auto_retriever.py
We have one method to generate collection name based on user's content path or url, but the generated name may not follow collection naming rule of the vector DB, we also can't use the timestamp as default name since the vector DB will be created each time running the RAG since the name of collection changes based on time
`close #859 ` 
> fix: Remove collection name generator in auto_retriever

- .github/workflows/build_package.yml
- .github/workflows/pytest_package.yml
- camel/loaders/firecrawl_reader.py
- examples/loaders/firecrawl_example.py
- poetry.lock
- pyproject.toml
- test/loaders/test_firecrawl.py
> feat: add firecrawl map endpoint

- .github/workflows/publish_docker_image.yml
Update GitHub Workflow, so that building and publishing GHCR packages will be automatically processed when a new release is published.
> chore: Add docker image building into CI/CD

- camel/retrievers/vector_retriever.py
- test/retrievers/test_vector_retriever.py
Add a RaiseValue exception when the storage is empty to prevent index out of range errors.
Currently, when attempting to access elements in storage and it is empty, an "IndexError: list index out of range" occurs. This change introduces a RaiseValue exception, which provides a more meaningful error message.
> fix: vector_retriever

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
- camel/__init__.py
- camel/retrievers/auto_retriever.py
- docs/conf.py
- docs/get_started/installation.md
- poetry.lock
- pyproject.toml
we used the meta data from unstructured io `Element` to check whether the file with same name has been modified, but this property has been removed in unstructured io v0.14.0 we are currently using, which makes the file modify check feature not available, so I remove this check temporarily before we find other way to do file modify check
> fix: remove file modify check for auto retriever

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
- camel/__init__.py
- camel/retrievers/vector_retriever.py
- docs/conf.py
- docs/cookbooks/agents_message.ipynb
- docs/cookbooks/agents_prompting.ipynb
- docs/cookbooks/agents_society.ipynb
- docs/cookbooks/agents_tracking.ipynb
- docs/cookbooks/agents_with_memory.ipynb
- docs/cookbooks/agents_with_rag.ipynb
- docs/cookbooks/agents_with_tools.ipynb
- docs/cookbooks/create_your_first_agent.ipynb
- docs/cookbooks/create_your_first_agents_society.ipynb
- docs/cookbooks/critic_agents_and_tree_search.ipynb
- docs/cookbooks/embodied_agents.ipynb
- docs/cookbooks/knowledge_graph.ipynb
- docs/cookbooks/model_speed_comparison.ipynb
- docs/cookbooks/roleplaying_scraper.ipynb
- docs/cookbooks/task_generation.ipynb
- docs/cookbooks/video_analysis.ipynb
- docs/cookbooks/workforce_judge_committee.ipynb
- docs/get_started/installation.md
- docs/key_modules/workforce.md
- pyproject.toml
Unstructured IO added `orig_elements` into element metadata, but the `orig_elements` seems encoded representation of the original content, which could be very long, we need to put the element metadata as payload, which has limitation for the input length, this could lead to potential bug
> fix: Remove orig_elements in unstructured element metadata

- camel/toolkits/google_scholar_toolkit.py
After discussed with @koch3092 , it's necessary to support `author` assignment to improve performance, so that if there's `author` value obtained, it would be used for `get_author_publications` and `get_publication_by_title` directly
`close #1121` 
> feat: google scholar toolkit support `author` assignment

- camel/configs/__init__.py
- camel/configs/yi_config.py
- camel/models/__init__.py
- camel/models/model_factory.py
- camel/models/yi_model.py
- camel/types/enums.py
- camel/types/unified_model_type.py
- camel/utils/__init__.py
- camel/utils/token_counting.py
- docs/key_modules/models.md
- examples/models/azure_openai_model_example.py
- examples/models/gemini_model_example.py
- examples/models/litellm_model_example.py
- examples/models/mistral_model_example.py
- examples/models/ollama_model_example.py
- examples/models/openai_compatibility_model_examples/nemotron.py
- examples/models/openai_compatibility_model_examples/qwen.py
- examples/models/reka_model_example.py
- examples/models/togetherai_model_example.py
- examples/models/vllm_model_example.py
- examples/models/yi_model_example.py
- examples/models/zhipuai_model_example.py
- test/models/test_yi_model.py
This PR adds support for the [Yi-series LLM models](https://platform.lingyiwanwu.com/), including yi-lightning, yi-large, yi-medium, and yi-large-turbo. The addition of Yi-series models enhances the platform’s capabilities, providing support for a broader range of language models and enabling users to leverage different performance tiers.
Closes issue #1066.
> feat: Add support for 01 model platform

- camel/types/enums.py
- docs/key_modules/models.md
- examples/models/gemini_model_example.py
- test/models/test_gemini_model.py
This PR adds the newest [Gemini-Exp-114 model](https://ai.google.dev/gemini-api/docs/models/experimental-models), which is an experimental model from Google Gemini.
Closes issue #1187.
> feat: Add support for Gemini-Exp-1114 model (#1187)

- camel/toolkits/human_toolkit.py
Currently, when calling ask_human_via_console, the question will not appear in console, causing difficulty for the user. Because the logger.info() cannot be shown in the console. 
> fix: that user cannot see question when using human_toolkit

- camel/toolkits/human_toolkit.py
Setting a new logging level with level 30 is not recognized by ONNX Runtime (which uses level 2 for Warning). The simplest solution would be to use print and then use logger.info
`close #1257`
> fix: use print instead of customized logger for human tool

- camel/configs/mistral_config.py
Fixes compatibility issue with Mistral SDK 1.2.0 which removed `min_tokens` parameter from `Chat.complete()`. References #1266 .
> fix: Remove deprecated `min_tokens` parameter from mistral config.

- camel/models/anthropic_model.py
- camel/utils/token_counting.py
Fixes issue when anthropic package isn't installed
There was an error where the anthropic package not being present would cause an error to be thrown from commons.py
> Fix: Import anthropic package when used since it's optional

- camel/datahubs/huggingface.py
- camel/datahubs/models.py
fix: when the user does not use huggingface record preset fields, the preset fields will be ignored.
close #1324
> fix: when the user does not use huggingface record preset fields, the preset fields will be ignored.

- apps/agents/agents.py
- apps/agents/test/test_agents.py
app code is using an older style of chaining Gradio events that's no longer supported in newer versions of Gradio
`close #1333` 
> fix: camel app AttributeError

- camel/datagen/self_instruct/self_instruct.py
- camel/datagen/self_instruct/templates.py
sample new instruction pool before updating the existing function
Fixed similarity bug
> fix: sample new instruction pool before updating the existing function

- .env
- .github/workflows/build_package.yml
- .github/workflows/pytest_apps.yml
- .github/workflows/pytest_package.yml
- camel/configs/__init__.py
- camel/configs/internlm_config.py
- camel/models/__init__.py
- camel/models/internlm_model.py
- camel/models/model_factory.py
- camel/types/enums.py
- camel/types/unified_model_type.py
- docs/key_modules/models.md
- examples/models/internlm_model_example.py
- test/models/test_internlm_model.py
Integrate InternLM models including  internlm3-latest, internlm3-8b-instruct, internlm2.5-latest,  internlm2-pro-chat via API calling 
`close #1326` 
> feat: Integrate InternLM models

- .env
- .github/workflows/build_package.yml
- .github/workflows/pytest_apps.yml
- .github/workflows/pytest_package.yml
- camel/configs/__init__.py
- camel/configs/moonshot_config.py
- camel/models/__init__.py
- camel/models/model_factory.py
- camel/models/moonshot_model.py
- camel/types/enums.py
- camel/types/unified_model_type.py
- docs/key_modules/models.md
- examples/models/moonshot_model_example.py
- test/models/test_moonshot_model.py
Integrating moonshot models.
close #1524 
integrating moonshot models
> feat: Integrate moonshot models to camel

- camel/types/enums.py
- examples/models/gemini_model_example.py
- test/models/test_gemini_model.py
Support Gemini 2.0 flash thinking and pro
> chore: Support Gemini 2.0 flash thinking and pro

- docs/cookbooks/advanced_features/agents_with_tools_from_Composio.ipynb
Fix the DeprecationWarning from Composio.
> UserWarning: Action.GITHUB_ACTIVITY_STAR_REPO_FOR_AUTHENTICATED_USER is deprecated and will be removed. Use Action.GITHUB_STAR_A_REPOSITORY_FOR_THE_AUTHENTICATED_USER instead.
Fixes #1575 
> docs(cookbooks): Fix the DeprecationWarning from Composio (issue-1575)

- camel/datagen/self_instruct/self_instruct.py
Improve the SelfInstructPipeline by setting the ensure_ascii parameter to False in the json.dump function. This change allows non-ASCII characters to be written directly, significantly enhancing the human readability of the output JSON file.
Fixes #1611 
> feat(datagen): Enhance JSON Dump in SelfInstructPipeline for Non-ASCII Character Readability

- docs/key_modules/workforce.md
This PR fixes the incorrect hyperlink in the Workforce documentation. The previous link was redirecting to the same page instead of the relevant cookbook.
> docs: Correct hyperlink for Hackathon Judge Committee

- docs/cookbooks/data_generation/self_instruct_data_generation.ipynb
The incorrect link is: `https://raw.githubusercontent.com/camel-ai/camel/master/examples/synthetic_datagen/self_instruct/seed_tasks.jsonl`  
Fixes #1609 
> docs(cookbooks): Fix incorrect URL in self_instruct_data_generation.ipynb

- camel/models/openai_model.py
- test/datahubs/test_huggingface.py
Keep strict in tool schema for openai api calling
> fix: Keep `strict` in tool schema

- camel/verifiers/__init__.py
- camel/verifiers/models.py
- camel/verifiers/python_verifier.py
- examples/verifier/python_verifier_example.py
- test/verifiers/test_python_verifier.py
This PR adds a first implementation of a PythonVerifier that is reusable for anything that is only dependent on Python packages.
This PR also includes a example usage, showing the verifier in action.
> feat: Python Verifier implementation

- camel/agents/chat_agent.py
- camel/models/model_manager.py
Update ModelManager error message for one model
> chore: Update ModelManager error message for one model

- camel/toolkits/__init__.py
- camel/toolkits/page_script.js
- camel/toolkits/web_toolkit.py
- examples/toolkits/web_toolkit.py
- pyproject.toml
- uv.lock
> feat: Add WebToolkit from owl

- camel/toolkits/web_toolkit.py
Remove `text = text.replace("`", '"')` to prevent potential text truncation and modify `observe_prompt` to standardize JSON output.
> fix: Update web_toolkit.py

- README.md
Fix link to Camel document page. There is a URL redirect error, previously https://www.docs.camel-ai.org doesn't route to https://docs.camel-ai.org. This PR is just to update the correct URL.
> docs: fix URL link to Camel document page

- camel/models/openai_compatible_model.py
- test/models/test_openai_compatible_model.py
This PR fixes an issue in the `OpenAICompatibleModel` initializer. Previously, the API key and URL retrieved from the environment variables were assigned to member variables `self.api_key` and `self.url`, but the parent class constructor was still using the original parameters `api_key` and `url` instead of the updated ones. This bug makes the environment variables ineffective.
I fixed this and wrote a simple test for `OpenAICompatibleModel`.
Note: Seems that there's no such an issue mentioning this.
> fix: api_key and base_url set in environment is not effective for OpenAICompatibleModel

- camel/toolkits/file_write_toolkit.py
- test/toolkits/test_file_write_toolkit.py
Solves issue in OWL - https://github.com/camel-ai/owl/issues/346
file names generated from video titles (or other metadata) often include spaces and special characters
when calls ytdlp it passes these strings directly 
need to sanitize the way `file_write_toolkit` works - removes dot(.) dash(-) with underscore(_)
added a test function for the same 
> fix: postprocessing error for yt-dlp by sanitizing file names in FileWriteToolkit

- docs/cookbooks/basic_concepts/create_your_first_agent.ipynb
- docs/get_started/installation.md
- docs/key_modules/memory.md
- docs/key_modules/retrievers.md
- docs/key_modules/tasks.md
- docs/key_modules/tools.md
The cookbook link was outdated in the docs and added a missing import.
> fix cookbook link + missing import for tools section

- camel/toolkits/code_execution.py
This PR make the default selection for sanbox to subprocess in the Code_execution Toolkit.
Links #1920
> chore: make the default selection for sanbox to subprocess in the Code_execution Toolkit.

- camel/models/groq_model.py
This PR addresses the stream flag turned off in groq.
I noticed that the docs for it mentioned it can stream - https://console.groq.com/docs/text-chat
> fix: stream prop for groq

- camel/toolkits/__init__.py
- camel/toolkits/thinking_toolkit.py
- examples/toolkits/thinking_toolkit.py
- examples/toolkits/thinking_toolkit_example.py
- test/toolkits/test_thinking_toolkit.py
> feat: add think toolkit

- camel/models/aiml_model.py
- camel/models/anthropic_model.py
- camel/models/azure_openai_model.py
- camel/models/base_audio_model.py
- camel/models/base_model.py
- camel/models/deepseek_model.py
- camel/models/gemini_model.py
- camel/models/groq_model.py
- camel/models/internlm_model.py
- camel/models/model_factory.py
- camel/models/moonshot_model.py
- camel/models/nemotron_model.py
- camel/models/nvidia_model.py
- camel/models/ollama_model.py
- camel/models/openai_audio_models.py
- camel/models/openai_compatible_model.py
- camel/models/openai_model.py
- camel/models/openrouter_model.py
- camel/models/qwen_model.py
- camel/models/samba_model.py
- camel/models/sglang_model.py
- camel/models/siliconflow_model.py
- camel/models/stub_model.py
- camel/models/togetherai_model.py
- camel/models/vllm_model.py
- camel/models/yi_model.py
- camel/models/zhipuai_model.py
This PR adds two ways to add timeout to the models
1. Parameter passing
2. From the env variables
Link #1946
> feat: adding timeout for basemodel backend

- camel/verifiers/python_verifier.py
The current Python verifier has a bug in the string comparison part. `repr` function was added for the deleted code, but str can be evaluated using `literal_eval` & `repr`. As a result, the line sol_val = None is never actually executed, and the fallback code for string comparison (# Fallback: string comparison) is never reached (it's effectively unreachable).
Currently, string comparison cases cannot be handled properly.
> fix: python verifier does not handle string comparison properly

- camel/toolkits/function_tool.py
- camel/utils/commons.py
Fixed a bug: When adding the timeout feature to the FunctionTool object method, keep the synchronous and asynchronous method feature to support asynchronous methods as FunctionTool calls.
> fix: functiontool supports asynchronous functions

- camel/agents/chat_agent.py
This PR adds an explicit warning to users to use more suited models in case of structured output failure in Workforce.
Fixes #2054
> chore: explicit model usage warnings for workforce

- .env
- camel/toolkits/mcp_toolkit.py
- test/toolkits/test_video_download_function.py
Raise exceptions instead of catch-to-log or returning them to the agent in MCP tools.
Whether an exception is recoverable and how to recover from one should be the caller's responsibility in these cases.
Per [mcp's guidelines](https://modelcontextprotocol.io/docs/concepts/tools#error-handling), tools should report errors via response objects. So an exception raised via an MCP tool will be related to the protocol itself or another issue outside the agent's responsibility.
If the caller (e.g. an application developer) wants agents to be able to work around issues outside their control, like if an MCP server stops responding, they can wrap the step function with an except and give agents a chance to recover or work around on their own. Developers might want to do this for certain types of …
> fix: improve error handling and resource cleanup in MCP toolkit

- camel/extractors/python_strategies.py
- test/extractors/test_python_strategies.py
The extractor was not working correctly with single boxed statements.
> fix: Enable extractor to handle single boxed backslashes

- camel/toolkits/mcp_toolkit.py
- test/toolkits/test_mcp_toolkit.py
> fix: missing-fields-when-converting-mcp-toolkit-inputschema-to-openai-schema

- test/toolkits/test_pyautogui_toolkit.py
These KeyError: 'DISPLAY' failures are happening because pyautogui requires a display environment (like X11 on Linux) to control the mouse/keyboard or take screenshots. When running in headless CI environments (like GitHub Actions), there's no display available, hence the 'DISPLAY' variable is missing.
> fix: pydutogui test

- .env
- camel/configs/__init__.py
- camel/configs/lmstudio_config.py
- camel/models/__init__.py
- camel/models/lmstudio_model.py
- camel/models/model_factory.py
- camel/types/enums.py
- camel/types/unified_model_type.py
- examples/models/lmstudio_model_example.py
- test/models/test_aws_bedrock_model.py
- test/models/test_lmstudio_model.py
Integrates lmstudio for local model support
Links #2190
> lmstudio integration

- camel/storages/vectordb_storages/milvus.py
- test/storages/vector_storages/test_milvus.py
The current implementation only executes the loop once because the outer list has only one element. This fix ensures that all results are processed and returned to match the requested top_k parameter.
Add two test cases to verify the fix for the Milvus query bug:
- test_milvus_return_multiple_results: Verifies the fixed implementation correctly returns all top_k results
- test_milvus_bug_single_result: Simulates the buggy behavior before the fix, where only a single result was returned regardless of top_k value
> fix: milvus query

- camel/societies/workforce/role_playing_worker.py
- camel/societies/workforce/single_agent_worker.py
This pull request fixes two cases where coroutine functions were not properly awaited within async task processing methods.
- In `role_playing_worker.py`, the `role_play_session.step()` call is now awaited.
- In `single_agent_worker.py`, the `worker.step()` call is now awaited.
Without `await`, coroutine objects are returned instead of their execution results, which can lead to unexpected behavior and errors like:
- `cannot pickle coroutine object`
- silent failures in task processing
This fix ensures that tasks are correctly executed within the async framework.
> fix: await bug in Workforce logic

- camel/configs/qwen_config.py
- camel/models/qwen_model.py
- camel/types/enums.py
- examples/models/qwen_model_example.py
> feat: update qwen_model to support qwen3

- camel/toolkits/mcp_toolkit.py
Pass the timeout seconds to the MCP session. Without this, it will use the default which is 5 currently.
I make timeout non-optional, since one will be set regardless by mcp. It could be desirable to accept a None-able timeout where `None` means to defer to whichever default timeout the underlying library has set, though I don't expect this to be frequently desired and people will be happy with a reasonable default, and many unaware of the underlying library could expect `None` to mean "no timeout" which would lead to greater surprise.
Timeouts beyond 5 seconds are useful for long-running MCP tools. Excessively long timeouts are also useful for enabling event-based systems (this is my need for this)
> feat: Pass timeout to MCP session

- apps/agents/agents.py
- apps/data_explorer/data_explorer.py
- apps/dilemma/dilemma.py
This small PR resolves the `logger.warn` deprecation warnings:
```python
/home/runner/work/camel/camel/apps/data_explorer/data_explorer.py:76: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
> fix: migrate to `logger.warning`

- camel/__init__.py
- pyproject.toml
- test/test_all_exports.py
Fixes #2367, a small bug
- [] I have updated the tests accordingly (*required for a bug fix or a new feature*)
- [] I have updated the documentation if needed:
- [] I have added examples if this is a new feature
> fix: Remove 'camel' from '__all__' list in 'camel/__init__.py'

- camel/types/enums.py
- docs/key_modules/models.md
- examples/models/gemini_model_example.py
The previously model type Gemini-2.0-Flash listed in `camel/types/enums.py` is linked to the Gemini-2.0-Flash-Experimental model. The latter model has a request limit of 10 RPM for users below Tier 3, which can easily lead to a `RESOURCE_EXHAUSTED` issue when running with more agents simultaneously. 
In addition to correcting the mapping for the two models, I added two model types of Gemini (`GEMINI_2_5_FLASH_PREVIEW` and `GEMINI_2_0_FLASH_LITE`) and updated the corresponding docs.
> feat: update Gemini model types, fix Gemini-2.0-Flash matching issue

- examples/usecases/aci_mcp/README.md
- examples/usecases/aci_mcp/aci_toolkit_camel.py
- examples/usecases/aci_mcp/camel_mcp_aci.py
- examples/usecases/aci_mcp/create_config.py
- examples/usecases/aci_mcp/env.example
changes made to - https://github.com/camel-ai/camel/pull/2490 
> chore: minor changes #2490

- camel/datasets/models.py
This PR addresses a `PydanticDeprecatedSince20` warning by updating the `DataPoint.to_dict()` method to use the Pydantic V2 API. Changes:
- Replaced `self.dict()` with `self.model_dump()` in `camel/datasets/models.py`.
This change ensures compatibility with Pydantic V2 and resolves deprecation warnings previously observed in [CI log](https://github.com/camel-ai/camel/actions/runs/15509708129/job/43669032243#step:4:410).
> fix: migrate Pydantic to new interface

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/workflows/build_package.yml
- camel/__init__.py
- camel/agents/mcp_agent.py
- camel/toolkits/function_tool.py
- camel/toolkits/mcp_toolkit.py
- camel/utils/mcp_client.py
- docs/conf.py
- examples/toolkits/playwright_mcp_toolkit.py
- pyproject.toml
- test/toolkits/test_generate_openai_tool_schema.py
- uv.lock
strict mode is required when do structured output with tool call, but for MCP toolkits we can't ensure the tool schema would follow strict mode, to support mcp toolkit could run in workforce (which requires structured output), we set all tool schema follow strict mode, this is also suggested by openai
> feat: Set tool schema follow strict mode

- camel/configs/vllm_config.py
vLLM supports some parameters that are not supported by OpenAI, top_k, chat_template_kwargs for example. You can pass these parameters to vLLM using the OpenAI client in the extra_body parameter of your requests.
In this way, you can call Qwen3 model with enable_thinking.
vllm_model = ModelFactory.create(
model_platform=ModelPlatformType.VLLM,
model_type=MODEL_NAME,
model_config_dict={"temperature": 0.0, "extra_body":{
"chat_template_kwargs": {"enable_thinking": False}
}},
url="http://localhost:33949/v1",
api_key="EMPTY",
)
If you are unsure about any of these, don't hesitate to ask. We are here …
> add extra_body in vllm config

- camel/interpreters/docker_interpreter.py
The `_create_file_in_container` function in `camel/interpreters/docker_interpreter.py` is used for executing the code in  and copying it into docker, the encoded data is transmitted, but the calculated binary length is the unencoded data.
> chore: _create_file_in_container method bug in Docker interpreter 

- .pre-commit-config.yaml
Updates the pre-commit configuration to ensure mypy runs using the project's virtual environment rather than the system installation.
The current pre-commit hook configuration uses language: python, which causes pre-commit to look for mypy in the system environment (e.g., pyenv global installation) instead of using the project's virtual environment managed by uv.
Fixes #2854 
> fix: pre-commit mypy hook to use project dependencies

- camel/toolkits/hybrid_browser_toolkit/browser_session.py
- camel/toolkits/hybrid_browser_toolkit/hybrid_browser_toolkit.py
- examples/toolkits/hybrid_browser_toolkit_example.py
- test/toolkits/test_hybrid_browser_toolkit.py
Implement monotonic tab ID generator to fix tab index invalidation bugs in the browser toolkit.
The existing tab management system used array indices which caused issues when tabs were closed:
- Closing a tab shifted all subsequent tab indices
- This led to tab index invalidation and incorrect tab references
- Users could lose track of their intended tabs after closures
Replace the array-based system with a dictionary-based approach using monotonic IDs:
**Key Changes:**
- **TabIdGenerator class**: Thread-safe monotonic counter generating sequential IDs (`tab-001`, `tab-002`, etc.)
- **Dictionary storage**: `Dict[str, Page]` instead of `List[Page]` for stable references
- **Updated API methods**: All tab management functions now use string IDs instead of indices
- **Backward …
> fix: replace tab index system with monotonic ID generator

- camel/utils/mcp_client.py
https://github.com/camel-ai/camel/issues/2859
Fixes Windows subprocess cleanup issue in MCPClient that causes "ValueError: I/O operation on closed pipe" errors during program shutdown.
Problem: When using MCPToolkit on Windows, users experience warnings about closed pipes and event loop errors during program termination. This occurs because the asyncio event loop closes before subprocess cleanup can complete properly.
Solution: Added a small delay (0.01 seconds) specifically for Windows in the _cleanup_connection method of MCPClient. This allows sufficient time for subprocess resources to be properly released before the event loop shuts down.
If you are unsure about any of these, don't hesitate to ask. We are …
> fix : ACI Windows MCPToolkit fix

- camel/toolkits/search_toolkit.py
- examples/toolkits/search_google_with_exclusion.py
After thinking carefully about PR #2901, I think it is better to allow users to set url domains to exclude from the `__init__` function of SearchToolkit, rather than from the specific `search_google` function. The specific functions are typically called by LLMs rather than used by human users.
The current version only supports excluding domains from `search_google`, and it can be extended to support other search toolkits in the future.
> enhance:  Enhance PR #2901, excluding domains from SearchToolkit definition rather than search_google function

- camel/storages/key_value_storages/mem0_cloud.py
- test/storages/key_value_storages/test_mem0_cloud.py
This PR fixes critical integration issues between CAMEL-AI's `Mem0Storage` and the mem0.ai cloud service. The integration was broken due to API changes in both CAMEL-AI and mem0 SDK. This PR provides minimal fixes to restore functionality.
1. **ChatHistoryMemory missing required argument**: The `context_creator` parameter became mandatory but wasn't documented in integration examples
2. **Incorrect API method call**: `Mem0Storage.clear()` was calling non-existent `delete_user()` instead of `delete_users()`
3. **Deprecation warning**: Missing `output_format` parameter in mem0 API calls
4. **Flaky integration test**: Skipped the integration test that was failing due to API-specific timing issues
- Fixed `delete_user()` → `delete_users()` in the `clear()` method
- Added …
> bug: mem0 api mismatch fix

- docs/mcp/camel_toolkits_as_an_mcp_server.md
During markdown rendering, the code blocks within the <CodeBlock></CodeBlock> tags failed to produce correct line breaks, which impaired readability. Therefore, this bug was fixed using markdown syntax (Note that adding the "white-space: pre-wrap" style declaration did not work).
Before modification:
from camel.toolkits import ArxivToolkit import argparse
parser = argparse.ArgumentParser( description="Run Arxiv Toolkit as an MCP server." ) parser.add_argument( "--mode", choices=["stdio", "sse", "streamable-http"], default="stdio", help="Select MCP server mode." ) args = parser.parse_args()
toolkit = ArxivToolkit() toolkit.mcp.run(args.mode)
After modification:
```python
from camel.toolkits import ArxivToolkit 
import argparse
parser = argparse.ArgumentParser( 
description="Run Arxiv …
```
> fix code block rendering line break bug

- .github/workflows/build_package.yml
- .github/workflows/pytest_package.yml
- camel/configs/__init__.py
- camel/configs/nebius_config.py
- camel/models/__init__.py
- camel/models/model_factory.py
- camel/models/nebius_model.py
- camel/types/enums.py
- camel/types/unified_model_type.py
- docs/mintlify/key_modules/models.mdx
- examples/models/nebius_model_example.py
- test/models/test_nebius_model.py
This PR adds support for Nebius AI Studio as a new model provider.
- NebiusModel class with OpenAI-compatible API support
- 7 available models including GPT-OSS, GLM-4.5, DeepSeek, LLaMA, and Mistral
- Configuration class and comprehensive tests
- Usage example
- GPT-OSS (120B & 20B)
- GLM-4.5 
- DeepSeek V3 & R1
- LLaMA 3.1 70B
- Mistral 7B Instruct
Fixes #3045
> Feat: Add Nebius AI Studio integration

- camel/storages/vectordb_storages/oceanbase.py
add_index_param method does not exist in pyobvector, it has been checked, and it does not exist in various versions
Close #3222 
> fix(oceanbase): fix vector index creation for oceanbase

- camel/societies/workforce/task_channel.py
- camel/societies/workforce/workforce.py
- examples/workforce/human_in_the_loop/simple_hotkey_demo.py
- examples/workforce/workforce_multitask_with_skip.py
Renamed for clarity:
- _independent_task_queue → _task_queue
- get_independent_tasks() → get_task_queue()
Simplified API:
- Removed is_independent parameter from add_task()
- Removed get_independent_tasks() wrapper method
- Direct implementation of add_task()
API Before/After:
```
add_task(content, is_independent=True)
get_independent_tasks()
add_task(content,as_subtask=True)
get_task_queue()
```
> enhance: support independent task queue for workforce PR3232
