camel-ai/camel

- camel/agents/chat_agent.py
- camel/agents/role_playing.py
- camel/human.py
- camel/messages.py
- examples/ai_society/role_playing_with_human.py
- examples/code/role_playing_multiprocess.py
- test/test_messages.py
Fix the hard coded `self.update_messages(output_messages[0])` (https://github.com/lightaime/camel/issues/88)
> Fix update messages and add docstrings and tests

- setup.py
https://stackoverflow.com/questions/1612733/including-non-python-files-with-setup-py
> Add prompt template txts into package

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
> Add contributing guidelines

- .github/workflows/documentation.yaml
> Update `publish_dir` of `documentation.yaml`

- docs/README.md
- docs/camel.messages.rst
- docs/get_started/code_prompt.md
- docs/get_started/text_prompt.md
- docs/index.rst
- test/prompts/test_prompt_base.py
> Add tutorial for `CodePrompt`

- camel/agents/embodied_agent.py
- test/agents/test_embodied_agent.py
- test/messages/test_message_base.py
> Refactor `EmbodiedAgent` and modify tests

- camel/agents/embodied_agent.py
#155 was merged without resolving comments accidentally. This PR resolves them.
> Fix `EmbodiedAgent` according to #155

- camel/utils.py
- examples/ai_society/role_playing_multiprocess.py
- examples/code/role_playing_multiprocess.py
I added automatic downloading of task files from Google Drive for code and ai society. Fixed https://github.com/camel-ai/camel/issues/156
> Autodownload tasks

- CONTRIBUTING.md
- camel/agents/critic_agent.py
- camel/agents/role_playing.py
- camel/configs.py
- camel/generators.py
- camel/human.py
- camel/messages/base.py
- camel/messages/chat_messages.py
- camel/prompts/base.py
- camel/prompts/prompt_templates.py
- camel/utils.py
- examples/code/role_playing_multiprocess.py
- test/agents/test_role_playing.py
- test/messages/test_chat_message.py
- test/messages/test_message_base.py
Cleaning up mypy errors.
Partially solves the issue #159
> Cleanup mypy errors

- apps/agents/agents.py
- examples/ai_society/role_playing.py
- examples/ai_society/role_playing_multiprocess.py
- examples/ai_society/role_playing_with_critic.py
- examples/ai_society/role_playing_with_human.py
- examples/code/role_playing_multiprocess.py
- examples/misalignment/role_playing_multiprocess.py
- examples/misalignment/role_playing_with_human.py
Fixes:
Prints were broken in examples/ai_society/role_playing.py and other examples.
Bug was introduced in:
0621ed8 Extracted ChatAgentResponse class, API breaking change (#154)
> Fix roleplay API changes in examples and apps

- examples/summarization/gpt_solution_extraction.py
Improve the summarization solution extraction example by enabling user to specify input directories etc via argparse and minor clean the code.
Helpful for other users to learn `camel` usage from the summarization solution extraction example.
> [Examples] Improve the summarization solution extraction example

- camel/agents/role_playing.py
- test/agents/test_role_playing.py
Fixed typos. Part of https://github.com/camel-ai/camel/issues/163
> Fixed `model_type` typos in `RolePlaying`

- examples/ai_society/role_playing.py
> Fixed `model_type` typos in `role_playing.py` examples

- README.md
> chore(readme): update badges

- camel/agents/embodied_agent.py
- camel/utils/python_interpreter.py
- test/utils/test_python_interpreter.py
> fix: fix mypy errors in `PythonInterpreter`

- .github/workflows/linting.yaml
- .gitignore
- camel/agents/task_agent.py
- examples/ai_society/role_playing_multiprocess.py
- examples/code/role_playing_multiprocess.py
- examples/misalignment/role_playing_multiprocess.py
- pyproject.toml
- test/messages/test_chat_message.py
> Enable mypy action in CI

- test/agents/test_chat_agent.py
Sometimes `ChatAgent` unit test which tests whether stream and batch mode have same output (`test_chat_agent_batch_stream_same_output`) will raise error due to some extra new lines in the stream output. https://github.com/camel-ai/camel/actions/runs/5485571323/jobs/9994538405?pr=210
```
FAILED test/agents/test_chat_agent.py::test_chat_agent_batch_stream_same_output - assert "Sure, here's...p everything!" == "Sure, here's...p everything!"
- Sure, here's a classic one for you: Why don't scientists trust atoms? Because they make up everything!
+ Sure, here's a classic one for you:
+ 
+ Why don't scientists trust atoms?
+ 
+ Because they make up everything!
```
I can't find why this happened or even can't reproduce locally.
The only information I got is from ChatGPT 😂
```
The OpenAI ChatGPT …
```
> Fix flaky `test_chat_agent_batch_stream_same_output`

- apps/agents/agents.py
- apps/agents/test/test_agents.py
Switch layout between AI Society and Code in Agents App.
In actuality does not work well. If the language is set to C#, the chat progresses with Python. @lightaime 
Solves #148.
> Add Code society to Agents

- apps/agents/agents.py
- apps/agents/test/test_agents.py
Add language textbox in Agents app.
Closes #183 
> Add output language to Agents

- Makefile
> feat(Makefile): add `make format`

- .github/workflows/pytest_apps.yml
- examples/code/role_playing.py
Not all tests were enables in CI, hence a bug made its way to the code in examples.
> Enable slow tests in examples, fix an uncaught bug

- CONTRIBUTING.md
- camel/agents/task_agent.py
The `fork-and-pull-request` workflow can not pass tests with GitHub secretes. It is recommended to follow `checkout-and-pull-request` workflow for organization members.
> docs: add member PR instruction

- camel/functions/search_functions.py
- pyproject.toml
- test/functions/test_search_functions.py
Add a function search_wiki_by_api to improve Wikipedia search, and add a test funtion for it.
This function is base on an open issue: #235 [Feature Request] Improve Wikipedia search.
> add search_wiki_by_api

- camel/functions/search_functions.py
- examples/function_call/role_playing_with_function.py
- test/functions/test_search_functions.py
- Modified the API function calling by setting `auto_suggest` to be `False` to prevent the search word being modified. Without this, `KAUST` can be automatically modified to `KAIST`.
- Reference: https://stackoverflow.com/questions/66630711/the-wikipedia-api-seems-to-almost-always-get-the-word-in-question-wrong
- Set the temperature of assistant and user agents to be 0.0 for more stable behaviour and better reproducibility in the example.
-  Only kept the new `search_wiki` in `SEARCH_FUNCS` to not confuse the model. Otherwise the model need to consider 2 different functions performing essentially the same functionality.
Thanks @zhiyu-01 for updating the search functionality which simplifies the code and providing the good error handling mechanism.
close #256 
What types of changes does …
> Modified Wikipedia Search

- camel/configs.py
- camel/functions/search_functions.py
- camel/societies/role_playing.py
- examples/function_call/role_playing_with_function.py
- pyproject.toml
- test/agents/test_role_playing.py
- test/functions/test_search_functions.py
> Update the branch feature/role-generation from master

- README.md
- camel/functions/search_functions.py
> Add `wechat` account

- camel/utils/python_interpreter.py
> chore: fix typo in python_interpreter.py

- CONTRIBUTING.md
- camel/utils/python_interpreter.py
- test/utils/test_python_interpreter.py
> [Fix] More coverage for python interpreter

- docs/get_started/messages.md
Fix documentation for Using the Methods of the BaseMessage Class section.
> Update of `messages.md` document

- test/functions/test_search_functions.py
Fix bug in `test_search_wiki_with_ambiguity`
> Fix bug in `test_search_wiki_with_ambiguity`

- camel/societies/babyagi_playing.py
> Add `BabyAGI`reference

- README.md
Added `BabyAGI` to readme reference
> Added `BabyAGI` to readme reference

- CONTRIBUTING.md
- README.md
- camel/agents/task_agent.py
- camel/models/openai_model.py
- examples/ai_society/babyagi_playing.py
- examples/test/test_babyagi_example.py
> Added `OPENAI_API_BASE_URL` to openai_model reference (#338)

- apps/agents/README.md
Added an instruction to deploy changes to apps to HF spaces.
> Instruction for HF deployment

- .pre-commit-config.yaml
- poetry.lock
- pyproject.toml
After integrating mypy to precommit, the github workflows randomly failed. This is beacuse mypy install stubs dependency during checking, which crashed the cached environment. This PR fixes it by putting stubs dependencies in the `pyproject.toml`.
> chores: fix tests fail because of pre-commit changing

- camel/embeddings/base.py
- camel/embeddings/openai_embedding.py
- camel/types/enums.py
- test/embeddings/test_openai_embedding.py
* Extend base embedding model by generics.
* Rename embedding functions.
* Rename embedding model types.
> fix(embeddings): Fix embeddings names

- README.md
Updated citation to neurips format
> docs: Updated citation to neurips format

- camel/functions/unstructured_io_fuctions.py
- poetry.lock
- pyproject.toml
remove pandas and pathlib in toml file
> chores: Remove pandas and pathlib in toml file

- .github/workflows/publish_release.yml
- README.md
Publish github release in a workflow requires `contents: write` permission. This PR fix the release publish problem.
> chores: grant write permission to publish release workflow

- camel/storages/vectordb_storages/base.py
- camel/storages/vectordb_storages/qdrant.py
- test/storages/vector_storages/test_all_vectordbs.py
> merge vectorstorage into feature/retriieval_function

- camel/functions/unstructured_io_fuctions.py
- poetry.lock
- pyproject.toml
remove `stage for argilla` to support `pydantic` >2 which required by function call
add kwargs to partition function
> chores: polish unstructured io

- poetry.lock
- pyproject.toml
> Lock `pydantic` to 2

- camel/models/open_source_model.py
- poetry.lock
Add a fake openai API key to open source model to avoid OpenAIError like in step 1 of #415 
> add fake openai api key to open source model support

- test/storages/vector_storages/test_all_vectordbs.py
- test/storages/vector_storages/test_qdrant.py
> fix(storage): Fix vectordb storage tests

- poetry.lock
- pyproject.toml
In our current dependency setting we only installed the native version of unstructured, instead of complete set of extras catering to every document type.
When user try to use this model handle with different types of file they need to install extra dependencies which will conflict to our initial environment(e.g. pytorch version conflict when using unstructured to handle pdf)
`close #484 `
> chore: update unstructured library dependency

- camel/messages/func_message.py
When writing functions with no arguments, these functions are written to grab resources that are returned to the agents or call events.
The bug is regarding this line,
https://github.com/camel-ai/camel/blob/33a634aa03e4387a1513d94eb092f9e35ca8625b/camel/messages/func_message.py#L70
This line is verifying that the argument dictionary exist, the bug is regarding python interpreter
if the dictionary is empty this line would return True even if the dictionary exist.
`close #491 ` 
> [BUG] FunctionCallingMessage functions that have no arguments

- .github/workflows/build_package.yml
- .github/workflows/pytest_package.yml
- camel/utils/token_counting.py
fix #518 
waiting for ANTHROPIC_API_KEY secret added to this repository
> fix format and del unused import

- camel/functions/search_functions.py
- test/functions/test_search_functions.py
> quick fix: wolfram alpha docstring 

- README.md
- camel/__init__.py
- docs/get_started/setup.md
- pyproject.toml
> quick fix/pypi version use 0.1.3

- apps/agents/agents.py
- apps/data_explorer/data_explorer.py
> quick fix: gradio app logo url

- examples/misalignment/task_generation.py
fix errors in task_generation examples
https://github.com/camel-ai/camel/issues/208
> fix: errors in task_generation examples

- camel/configs/__init__.py
- camel/configs/anthropic_config.py
- camel/configs/base_config.py
- camel/configs/openai_config.py
Add `configs` folder
As mentioned in #526
> Add `configs` folder

- camel/agents/chat_agent.py
- camel/configs.py
- camel/configs/__init__.py
- camel/configs/anthropic_config.py
- camel/configs/base_config.py
- camel/configs/openai_config.py
- camel/types/enums.py
- examples/vision/object_recognition.py
- test/agents/test_chat_agent.py
- test/models/test_openai_model.py
Remove `ChatGPTVisionConfig` and `GPT_4_TURBO_VISION`.
This PR also includes the refactor of `configs.py` into `configs/` folder.
As mentioned in #526
> Remove `ChatGPTVisionConfig` and refactor configs

- docs/agents/single_agent.md
> docs: remove useless import

- camel/models/__init__.py
- camel/models/openai_audio_models.py
- camel/types/__init__.py
- camel/types/enums.py
- examples/openai_audio_models/openai_audio_models.py
- poetry.lock
- pyproject.toml
- test/models/test_openai_audio_models.py
Integrate OpenAI's text to speech and speech to text models
1. text_to_speech using `tts-1`, with chunking module to solve the character limitation 4096
2. speech_to_text using `whisper-1`, with chunking module to solve the size limitation 25mb
`close #547 `
> feat: Integrate OpenAI audio models

- camel/functions/__init__.py
- camel/functions/slack_function.py
- camel/functions/slack_functions.py
- poetry.lock
- pyproject.toml
- test/functions/test_slack_functions.py
Integrate slack functions into camel including:
1. create_slack_channel
2. join_slack_channel
3. leave_slack_channel
4. get_slack_channel_information
5. get_slack_channel_message
6. send_slack_message
7. delete_slack_message
refer: https://slack.dev/python-slack-sdk/web/index.html#files
`close #546` 
> feat: Integrate slack

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
- camel/__init__.py
- docs/conf.py
- docs/get_started/setup.md
- pyproject.toml
> release: version 0.1.4

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
- camel/__init__.py
- docs/conf.py
- docs/get_started/setup.md
- pyproject.toml
> release: v0.1.5

- .github/workflows/publish_release.yml
- README.md
- docs/conf.py
- docs/get_started/setup.md
- pyproject.toml
> fix: use 0.1.5.1 and revert change to release yml

- camel/models/__init__.py
- camel/models/anthropic_model.py
- camel/models/base_model.py
- camel/models/model_factory.py
- camel/models/ollama_model.py
- camel/models/open_source_model.py
- camel/models/openai_model.py
- camel/models/stub_model.py
- camel/types/enums.py
- examples/open_source_models/ollama.py
- examples/open_source_models/ollama_model.py
> feat: Integrate Ollama

- CONTRIBUTING.md
upadte contribution documentation, add code review guide and update release information
> docs: add code review guide

- poetry.lock
- pyproject.toml
remove anthropic from [tool.poetry.extras]
> fix: Update poetry dependency for anthropic

- README.md
- docs/get_started/setup.md
Polish camel installation part
> docs: Polish camel installation part

- camel/prompts/task_prompt_template.py
- camel/types/enums.py
- examples/vision/video_description.py
Fix video description naming
Originally the name is incorrect, rename to a better one
> Fix video description naming

- README.md
- docs/conf.py
- docs/get_started/setup.md
- pyproject.toml
> release:  v0.1.5.2

- camel/agents/chat_agent.py
- camel/functions/open_api_function.py
- camel/functions/slack_functions.py
Modify `ChatAgent` function call args json and make slack sdk optional
* I don't think we need the `.replace("'", "\"")` to parse to json in agent's `step_tool_call `. Adding this extra replace will result in some weird error.
* Now when I install camel with `pip install camel-ai==0.1.5.2` and run some example, will have following error
```
Traceback (most recent call last):
File "/Users/zecheng/code/social-simulation/main.py", line 9, in <module>
from social_agent.agents_generator import generate_agents
File "/Users/zecheng/code/social-simulation/social_agent/agents_generator.py", line 10, in <module>
from .agent import TwitterUserAgent
File "/Users/zecheng/code/social-simulation/social_agent/agent.py", line 10, in <module>
from social_agent.agent_action import TwitterAction
File …
```
> Modify `ChatAgent` function call args json and make slack sdk optional

- README.md
- docs/get_started/setup.md
> docs: Ollama doc

- README.md
- docs/conf.py
- docs/get_started/setup.md
- examples/test/test_role_description_example.py
- pyproject.toml
> release: v0.1.5.3

- examples/embeddings/vlm_embedding_example.py
> chore: Add example for vlm embedding

- examples/ai_society/role_playing_multiprocess.py
- examples/ai_society/role_playing_with_critic.py
- examples/ai_society/role_playing_with_human.py
- examples/embeddings/vlm_embedding_example.py
- examples/function_call/role_playing_with_functions.py
- examples/generate_text_embedding_data/single_agent.py
- examples/generate_text_embedding_data/task_generation.py
- examples/misalignment/role_playing_multiprocess.py
- examples/misalignment/role_playing_with_human.py
- examples/misalignment/task_generation.py
- examples/vision/object_recognition.py
We have updated the way to set model for agent, but didn't update the content in examples folder
> fix: update model calling for examples

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
- camel/__init__.py
- docs/conf.py
- docs/get_started/setup.md
- pyproject.toml
Release v0.1.5.5
Update README link to docker install
> release: v0.1.5.5

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
- camel/__init__.py
- camel/agents/knowledge_graph_agent.py
- docs/conf.py
- docs/get_started/setup.md
- pyproject.toml
- test/agents/test_knowledge_agent.py
> feat: Update knowledge graph agent for tutorial

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
- camel/__init__.py
- camel/configs/gemini_config.py
- camel/models/base_model.py
- camel/models/litellm_model.py
- camel/models/ollama_model.py
- camel/models/zhipuai_model.py
- docs/conf.py
- docs/get_started/setup.md
- pyproject.toml
get model's max token from config, set gemini library as optional
> fix: model token_limit and gemini dependency

- camel/agents/chat_agent.py
- camel/agents/critic_agent.py
- camel/agents/deductive_reasoner_agent.py
- camel/agents/embodied_agent.py
- camel/agents/knowledge_graph_agent.py
- camel/agents/role_assignment_agent.py
- camel/agents/search_agent.py
- camel/agents/task_agent.py
- camel/types/enums.py
- examples/vision/object_recognition.py
- test/agents/test_chat_agent.py
- test/agents/test_role_playing.py
- test/models/test_openai_model.py
Add `GPT_4O_MINI`, make it default to chatagent and some minor fixes
`GPT_4O_MINI` seems to be the model used to replace `GPT_3_5_TURBO` in the future
> feat: Add `GPT_4O_MINI`

- camel/configs/__init__.py
- camel/configs/anthropic_config.py
- camel/configs/base_config.py
- camel/configs/gemini_config.py
- camel/configs/groq_config.py
- camel/configs/litellm_config.py
- camel/configs/ollama_config.py
- camel/configs/openai_config.py
- camel/configs/vllm_config.py
- camel/configs/zhipuai_config.py
- examples/models/litellm_model_example.py
- examples/models/role_playing_with_claude.py
- test/models/test_anthropic_model.py
- test/models/test_litellm_model.py
#651 Integrate Pydantic but there is a issue when testing.
> feat: pydantic configs

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
- camel/__init__.py
- docs/conf.py
- docs/get_started/setup.md
- poetry.lock
- pyproject.toml
> release: V0.1.5.8

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
- camel/__init__.py
- camel/retrievers/auto_retriever.py
- camel/types/enums.py
- docs/conf.py
- docs/get_started/setup.md
- pyproject.toml
fix the bug and do the release
`close #768 ` 
> fix: Token number error for GPT3.5 turbo

- camel/agents/chat_agent.py
- docs/tutorials_and_cookbooks/agents_with_tools.md
- docs/tutorials_and_cookbooks/agents_with_tools_from_Composio.md
- examples/models/mistral_model_example.py
- examples/structured_response/json_format_reponse_with_tools.py
- examples/structured_response/json_format_response.py
- examples/tasks/task_generation.py
- examples/vision/image_crafting.py
- examples/vision/multi_condition_image_crafting.py
- examples/vision/multi_turn_image_refining.py
> fix: align with pydantic update

- .github/workflows/build_package.yml
fix: Could not install packages due to an OSError: [Errno 28] No space left on device
`close #802 `
> fix: Could not install packages due to an OSError: [Errno 28] No space left on device

- examples/workforce/multiple_single_agents.py
- examples/workforce/role_playing_with_agents.py
`.as_dict()` in ChatGPTConfig is used to get model_config_dict
model_config.__dict__ is deprecated
> fix: replace __dict__ with as_dict() in model_config

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
- camel/__init__.py
- camel/agents/chat_agent.py
- camel/agents/critic_agent.py
- camel/agents/deductive_reasoner_agent.py
- camel/agents/embodied_agent.py
- camel/agents/knowledge_graph_agent.py
- camel/agents/role_assignment_agent.py
- camel/agents/search_agent.py
- camel/agents/task_agent.py
- camel/utils/__init__.py
- camel/utils/commons.py
- docs/conf.py
- docs/get_started/setup.md
- examples/bots/telegram_bot.py
- examples/observability/agentops_track_roleplaying_with_function.py
- poetry.lock
- pyproject.toml
> fix: track_agent() got an unexpected keyword argument 'name' when without agentops

- camel/loaders/jina_url_reader.py
- test/embeddings/test_mistral_embedding.py
- test/loaders/test_jina_url_reader.py
change jina and mistral embedding tests into mock
> fix: change jina and mistral embedding tests into mock

- camel/models/mistral_model.py
Add agentops support for mistral model running
> feat: Add agentops support for mistral model running

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
- camel/__init__.py
- docs/conf.py
- docs/get_started/setup.md
- pyproject.toml
> release: v0.1.6.4

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
- camel/__init__.py
- camel/configs/gemini_config.py
- camel/configs/groq_config.py
- camel/configs/mistral_config.py
- camel/loaders/unstructured_io.py
- camel/retrievers/auto_retriever.py
- camel/retrievers/bm25_retriever.py
- camel/retrievers/vector_retriever.py
- camel/toolkits/retrieval_toolkit.py
- docs/conf.py
- docs/get_started/setup.md
- pyproject.toml
- test/loaders/test_unstructured_io.py
- test/retrievers/test_auto_retriever.py
change auto_retriever output format
#822 
> feat: Change auto_retriever output format

- camel/models/openai_compatibility_model.py
Add property for maximum token limit in OpenAICompatibilityModel
close #831 
> fix: Add property for maximum token limit in OpenAICompatibilityModel

- camel/types/enums.py
This PR improves the naming convention of the ModelPlatformType enum to enhance code readability and consistency. Specifically, it modifies the enum values by replacing the camel-case structure with a more standardized underscore-separated format.
This change is required to adhere to consistent naming conventions across the codebase, which improves readability and maintainability for developers. By making the enum values more intuitive and easier to understand, this change addresses part of the broader effort to improve code quality.
This PR closes #15213 by implementing the proposed naming convention changes.
If you are …
> fix: Improving naming covention of ModelPlatformType

- camel/types/enums.py
- docs/agents/single_agent.md
- examples/models/openai_compatibility_model_example.py
- examples/models/role_playing_with_open_source_model.py
- test/models/test_model_factory.py
This PR addresses the inconsistency in the ModelPlatformType Enum values. The Enum values have been updated to ensure clarity and consistency across the codebase. Additionally, the relevant documentation and text references have been revised to reflect these changes.
This change is required to resolve inconsistencies in the ModelPlatformType Enum values which could lead to potential misunderstandings or errors when using the Enum. By updating the Enum values and associated documentation, I aim to improve the clarity and maintainability of the code.
If you are unsure about any of these, don't hesitate to ask. We are here to …
> fix: Ensure Enum values are properly defined in ModelPlatformType

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
- camel/__init__.py
- docs/conf.py
- docs/get_started/setup.md
- pyproject.toml
> release: v0.1.6.6

- CONTRIBUTING.md
Added a comment to explicitly mention that all extra packages are needed to pass all tests.
#873 
> docs: Explicitly mention all extra packages are needed to pass all tests

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
- camel/__init__.py
- docs/conf.py
- docs/get_started/setup.md
- pyproject.toml
> release: v 0.1.6.7

- CNAME
add CNAME file for custom domain setting
> feat: add CNAME

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
- camel/__init__.py
- docs/conf.py
- docs/get_started/setup.md
- pyproject.toml
> release: v0.1.6.8

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
- camel/__init__.py
- camel/retrievers/auto_retriever.py
- camel/retrievers/vector_retriever.py
- docs/conf.py
- docs/get_started/setup.md
- pyproject.toml
Add max_characters setting to RAG
Support service bot developing
> feat: Add max_characters setting to RAG

- camel/retrievers/auto_retriever.py
- camel/retrievers/vector_retriever.py
- camel/toolkits/retrieval_toolkit.py
- camel/utils/constants.py
Add `top_k` and `similarity_threshold` to RetrievalToolkit
move `DEFAULT_TOP_K_RESULTS` and `DEFAULT_SIMILARITY_THRESHOLD`  to constants
add `auto_retriever` setting to init of RetrievalToolkit
`close #899 ` 
> feat: Add `top_k` and `similarity_threshold` to RetrievalToolkit

- camel/embeddings/openai_embedding.py
text-embedding-ada-002 doesn't support dimensions setting
`close #902 ` 
> fix: embedding dimensions setting

- camel/toolkits/__init__.py
- camel/toolkits/reddit_toolkit.py
- examples/function_call/reddit_examples.py
- poetry.lock
- pyproject.toml
- test/toolkits/test_reddit_functions.py
integrate reddit toolkit https://github.com/camel-ai/camel/issues/757
I have raised an issue to propose this change ([required](https://github.com/camel-ai/camel/issues) for new features and bug fixes)
> feat: integrate reddit toolkit

- camel/agents/chat_agent.py
Update message append logic for `handle_stream_response`
`close #915 `
> feat: Update message append logic for `handle_stream_response`

- camel/agents/chat_agent.py
- camel/configs/__init__.py
- camel/configs/samba_config.py
- camel/models/model_factory.py
- camel/models/ollama_model.py
- camel/models/samba_model.py
- camel/types/enums.py
- examples/models/samba_model_example.py
- test/models/test_samba_model.py
> feat: SambaVerse API support

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
- camel/__init__.py
- camel/models/ollama_model.py
- camel/models/vllm_model.py
- docs/conf.py
- docs/get_started/setup.md
- examples/models/ollama_model_example.py
- examples/models/vllm_model_example.py
- pyproject.toml
1. launch vLLM and Ollama servers in a subprocess when no url is given
2. release: v 0.1.7.0
> feat: Subprocess support for Ollma and vllm

- camel/models/samba_model.py
> fix: sambaverse hot fix

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
- camel/__init__.py
- camel/agents/chat_agent.py
- docs/conf.py
- docs/get_started/setup.md
- pyproject.toml
> fix: samba fastapi empty output

- cookbooks/task_generation.ipynb
- examples/tasks/task_generation.py
I have updated the tutorial to emphasize the usage of the CAMEL task module, including creating, evolving, and decomposing tasks.
> docs: Add tasks cookbook

- cookbooks/message_cookbook.ipynb
> docs: Add message cookbook

- docs/conf.py
- docs/key_modules/memory.md
- docs/key_modules/messages.md
- docs/key_modules/prompts.md
- docs/key_modules/tasks.md
- docs/key_modules/tools.md
> docs: core modules doc polish

- test/toolkits/test_search_functions.py
> fix: mock google api call

- .github/workflows/documentation.yml
- poetry.lock
- pyproject.toml
add pandoc for jupyter notebook doc
> feat: add pandoc for jupyter notebook doc

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
- camel/__init__.py
- camel/loaders/firecrawl_reader.py
- camel/models/mistral_model.py
- docs/conf.py
- docs/cookbooks/agents_message.ipynb
- docs/cookbooks/agents_prompting.ipynb
- docs/cookbooks/agents_society.ipynb
- docs/cookbooks/agents_tracking.ipynb
- docs/cookbooks/agents_with_memory.ipynb
- docs/cookbooks/agents_with_tools.ipynb
- docs/cookbooks/create_your_first_agent.ipynb
- docs/cookbooks/create_your_first_agents_society.ipynb
- docs/cookbooks/knowledge_graph.ipynb
- docs/cookbooks/task_generation.ipynb
- docs/get_started/setup.md
- examples/loaders/firecrawl_example.py
- pyproject.toml
- test/loaders/test_firecrawl.py
update with firecrawl and openai new version
> fix: update with firecrawl and openai new version

- docs/conf.py
remove index for code in notebook
> docs: remove index for code in notebook

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
- camel/__init__.py
- camel/agents/chat_agent.py
- docs/conf.py
- docs/get_started/setup.md
- examples/models/role_playing_with_sambanova.py
- pyproject.toml
support llama model with tool calling
> feat: llama model tool calling

- CONTRIBUTING.md
- camel/agents/chat_agent.py
- docs/cookbooks/create_your_first_agent.ipynb
- docs/cookbooks/create_your_first_agents_society.ipynb
- docs/key_modules/models.md
- examples/models/ollama_model_example.py
- examples/models/role_playing_with_sambanova.py
- poetry.lock
- pyproject.toml
update contribution guideline and poetry toml
> chore: update contribution guideline and poetry toml

- camel/models/openai_compatibility_model.py
- docs/get_started/installation.md
- docs/get_started/setup.md
- docs/index.rst
- docs/key_modules/models.md
Polish OpenAICompatibilityModel class.
Polish onboarding doc for model setup:
1. Split installation and api setup; 
2. put api & local model related part into models doc, and add hyperlinks in setup doc; 
3. provide examples of openai-compatible apis in models doc.
`close #988`
> docs: Polish model setup doc for better onboarding experience

- camel/loaders/unstructured_io.py
- camel/retrievers/vector_retriever.py
Update retriever IO[bytes] support
enhance retriever function #1001 
> feat: Add support to handle bytes for vector retrieval

- .github/workflows/build_package.yml
- .github/workflows/documentation.yml
- .github/workflows/pre_commit.yml
- .github/workflows/pytest_apps.yml
- .github/workflows/pytest_package.yml
add cicd test for qa branch
qa branch is used to handle with breaking updates
> feat: add cicd test for qa branch

- test/toolkits/test_search_functions.py
> chore: mock duckduckgo search test

- camel/loaders/unstructured_io.py
- camel/retrievers/vector_retriever.py
fix vector retrieval type hint
> fix: vector retrieval type hint

- camel/types/enums.py
- examples/models/mistral_model_example.py
- test/models/test_mistral_model.py
support mistral pixtral model
`close #931 ` 
> feat: support mistral pixtral model

- camel/messages/func_message.py
- camel/workforce/prompts.py
- camel/workforce/single_agent_worker.py
Improved the overall performance of the workforce and the output information quality.
> [Enhance] small improvement of workforce performance 

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
- camel/__init__.py
- docs/conf.py
- docs/get_started/installation.md
- pyproject.toml
- test/messages/test_func_message.py
update test_func_message
release v0.2.2
> fix: update test_func_message

- docs/get_started/setup.md
- docs/index.rst
- docs/key_modules/memory.md
- docs/key_modules/models.md
- docs/key_modules/retrievers.md
- docs/key_modules/tasks.md
- docs/key_modules/tools.md
- docs/key_modules/workforce.md
> docs: core module add link jump to cookbook

- examples/models/openai_compatibility_model_example.py
> chore: update openai compatibility example

- poetry.lock
- pyproject.toml
> chore: update dependency toml

- camel/configs/anthropic_config.py
- camel/models/anthropic_model.py
- camel/utils/token_counting.py
> chore: move anthropic as optional

- .github/workflows/publish_release.yml
Update CI/CD file, so that pre-release versions with "a" in tag will be released as pre-release.
> chore: update CI/CD

- README.md
> Small fix on `readme.md`

- README.md
- docs/cookbooks/create_your_first_agent.ipynb
first agent doc and readme update
> docs: first agent doc and readme update

- .github/workflows/build_package.yml
- .github/workflows/pytest_package.yml
> fix: add CHUNKR_API_KEY to workflow

- camel/types/enums.py
- camel/types/unified_model_type.py
- test/models/test_model_type.py
Fix the string representation of `ModelType`, and add the corresponding tests.
> fix: string representation of `ModelType`

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
- camel/__init__.py
- camel/agents/chat_agent.py
- camel/configs/__init__.py
- camel/configs/samba_config.py
- camel/models/samba_model.py
- docs/conf.py
- docs/cookbooks/agents_message.ipynb
- docs/cookbooks/agents_prompting.ipynb
- docs/cookbooks/agents_society.ipynb
- docs/cookbooks/agents_tracking.ipynb
- docs/cookbooks/agents_with_memory.ipynb
- docs/cookbooks/agents_with_rag.ipynb
- docs/cookbooks/agents_with_tools.ipynb
- docs/cookbooks/create_your_first_agent.ipynb
- docs/cookbooks/create_your_first_agents_society.ipynb
- docs/cookbooks/critic_agents_and_tree_search.ipynb
- docs/cookbooks/embodied_agents.ipynb
- docs/cookbooks/knowledge_graph.ipynb
- docs/cookbooks/model_speed_comparison.ipynb
- docs/cookbooks/roleplaying_scraper.ipynb
- docs/cookbooks/task_generation.ipynb
- docs/cookbooks/video_analysis.ipynb
- docs/cookbooks/workforce_judge_committee.ipynb
- docs/get_started/installation.md
- examples/models/samba_model_example.py
- poetry.lock
- pyproject.toml
fix llama tool call msg added multi times
remove samba fast api in model config and example code
release v 0.2.6
`close #1119` 
> fix: llama tool call msg & remove samba fast api

- docs/key_modules/workforce.md
- examples/models/openai_o1_example.py
> chore: update workforce doc and openai o1 example

- examples/models/openai_compatibility_model_examples/grok.py
add example code show how to call grok with `OPENAI_COMPATIBLE_MODEL`
`close #1108` 
> chore: add grok example

- camel/storages/vectordb_storages/qdrant.py
- test/storages/vector_storages/test_qdrant.py
- Added an explicit QdrantStorage.close_client() method to prevent concurrency conflicts in local storage access.
- Added QdrantStorage.update_payload(), which allows updating the vector's payload.
- Added filter functionality to QdrantStorage.query(), enabling searches using QdrantClient’s native Filter support.
- Added filter functionality to QdrantStorage.delete(), enabling delete operations using QdrantClient’s native Filter support.
- Added QdrantStorage.delete_collection(), which deletes the entire collection in the Qdrant storage.
close #989 
If you are unsure about any of these, don't hesitate to ask. We are here to …
> feat: Qdrant enhancement

- camel/societies/role_playing.py
Priority critic and task agent kwargs in RolePlaying
Set default model for RolePlaying
> chore: Priority critic and task agent kwargs in RolePlaying

- README.md
Update `readme.md` with more code sinppets, features, news and researchs.
https://github.com/camel-ai/camel/issues/1051
> doc: pdate `readme.md` with features and some main feature code sinppets

- camel/retrievers/vector_retriever.py
- test/retrievers/test_cohere_rerank_retriever.py
> feat: add param extra_payload for VectorRetriever.process()

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
- camel/__init__.py
- camel/agents/chat_agent.py
- docs/conf.py
- docs/cookbooks/agents_message.ipynb
- docs/cookbooks/agents_prompting.ipynb
- docs/cookbooks/agents_society.ipynb
- docs/cookbooks/agents_tracking.ipynb
- docs/cookbooks/agents_with_memory.ipynb
- docs/cookbooks/agents_with_rag.ipynb
- docs/cookbooks/agents_with_tools.ipynb
- docs/cookbooks/create_your_first_agent.ipynb
- docs/cookbooks/create_your_first_agents_society.ipynb
- docs/cookbooks/critic_agents_and_tree_search.ipynb
- docs/cookbooks/embodied_agents.ipynb
- docs/cookbooks/knowledge_graph.ipynb
- docs/cookbooks/model_speed_comparison.ipynb
- docs/cookbooks/roleplaying_scraper.ipynb
- docs/cookbooks/task_generation.ipynb
- docs/cookbooks/video_analysis.ipynb
- docs/cookbooks/workforce_judge_committee.ipynb
- docs/get_started/installation.md
- docs/key_modules/loaders.md
- pyproject.toml
- test/agents/test_chat_agent.py
fix the output_language setting in ChatAgent
release v0.2.7
`close #1164` 
> fix: output_language setting in ChatAgent

- camel/models/openai_model.py
> fix: update `n` type in OpenAI Model

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
- camel/__init__.py
- camel/societies/role_playing.py
- docs/conf.py
- docs/cookbooks/agents_message.ipynb
- docs/cookbooks/agents_prompting.ipynb
- docs/cookbooks/agents_society.ipynb
- docs/cookbooks/agents_tracking.ipynb
- docs/cookbooks/agents_with_memory.ipynb
- docs/cookbooks/agents_with_rag.ipynb
- docs/cookbooks/agents_with_tools.ipynb
- docs/cookbooks/create_your_first_agent.ipynb
- docs/cookbooks/create_your_first_agents_society.ipynb
- docs/cookbooks/critic_agents_and_tree_search.ipynb
- docs/cookbooks/embodied_agents.ipynb
- docs/cookbooks/knowledge_graph.ipynb
- docs/cookbooks/model_speed_comparison.ipynb
- docs/cookbooks/roleplaying_scraper.ipynb
- docs/cookbooks/task_generation.ipynb
- docs/cookbooks/video_analysis.ipynb
- docs/cookbooks/workforce_judge_committee.ipynb
- docs/get_started/installation.md
- docs/key_modules/loaders.md
- pyproject.toml
remove default self.model setting in RolePlaying, as the empty dict passed to ChatAgent would use the default model set in ChatAgent side
> fix: RolePlaying model setting would be override by default model

- camel/types/enums.py
- docs/cookbooks/agents_with_rag.ipynb
- docs/key_modules/models.md
- docs/key_modules/workforce.md
- examples/models/qwen_model_example.py
- test/models/test_model_factory.py
- test/models/test_qwen_model.py
support
QWEN_2_5_CODER_32B = "qwen2.5-coder-32b-instruct"
QWEN_2_5_72B = "qwen2.5-72b-instruct"
QWEN_2_5_32B = "qwen2.5-32b-instruct"
QWEN_2_5_14B = "qwen2.5-14b-instruct"
fix AutoRAG doc bug, workforce image bug
update model used in model factory test
> chore: add mode Qwen models, fix doc bug

- camel/toolkits/ask_news_toolkit.py
- examples/toolkits/ask_news_toolkit.py
upadte ask new example and api key setting
> chore: upadte asknews example and api key setting

- camel/agents/chat_agent.py
- camel/configs/openai_config.py
- camel/models/openai_model.py
- camel/types/__init__.py
- camel/types/openai_types.py
- examples/models/openai_structured_output_example.py
support openai structured output
`close #1197 ` 
> feat: support openai structured output

- docs/index.rst
> chore: update mission

- CONTRIBUTING.md
- README.md
- camel/personas/persona.py
- camel/personas/persona_hub.py
- docs/cookbooks/ingest_data_from_websites_with_Firecrawl.ipynb
- docs/index.rst
1. update personal hub based on review comment
2. update default model setting based on review comment
3. add docstring and naming principle to contribution guideline
> chore: update doc and small polish

- test/models/test_cohere_model.py
- test/runtime/test_remote_http_runtime.py
> fix pipeline

- CONTRIBUTING.md
- camel/toolkits/human_toolkit.py
- docs/index.rst
- examples/models/qwq_model_example.py
add example calling qwq with ollama
update human in the loop based on review comment
update doc based on review comment
`close #1235 `
> chore: add qwq model, update based on code review

- camel/schemas/__init__.py
- camel/schemas/base.py
- camel/schemas/openai_converter.py
- camel/utils/response_format.py
- examples/schema_outputs/openai_converter_example.py
- test/schema_outputs/test_openai_converter.py
> fix: Support Text to BaseModel

- camel/agents/chat_agent.py
- camel/configs/vllm_config.py
- camel/responses/agent_responses.py
> chore: polish PR 1236

- camel/types/enums.py
- test/models/test_azure_openai_model.py
> chore: add gpt 4o mini to azure openai ai

- camel/loaders/firecrawl_reader.py
remove api_keys_required for firecrawl to support self-deploy
> chore: remove api_keys_required for firecrawl to support self-deploy

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
- camel/__init__.py
- docs/conf.py
- docs/cookbooks/agents_message.ipynb
- docs/cookbooks/agents_prompting.ipynb
- docs/cookbooks/agents_society.ipynb
- docs/cookbooks/agents_tracking.ipynb
- docs/cookbooks/agents_with_memory.ipynb
- docs/cookbooks/agents_with_rag.ipynb
- docs/cookbooks/agents_with_tools.ipynb
- docs/cookbooks/create_your_first_agent.ipynb
- docs/cookbooks/create_your_first_agents_society.ipynb
- docs/cookbooks/critic_agents_and_tree_search.ipynb
- docs/cookbooks/embodied_agents.ipynb
- docs/cookbooks/ingest_data_from_websites_with_Firecrawl.ipynb
- docs/cookbooks/knowledge_graph.ipynb
- docs/cookbooks/model_speed_comparison.ipynb
- docs/cookbooks/roleplaying_scraper.ipynb
- docs/cookbooks/task_generation.ipynb
- docs/cookbooks/video_analysis.ipynb
- docs/cookbooks/workforce_judge_committee.ipynb
- docs/get_started/installation.md
- docs/key_modules/loaders.md
- pyproject.toml
> chore: release v0.2.11

- docs/cookbooks/customer_service_Discord_bot_with_agentic_RAG.ipynb
> fix: bot cookbook format

- camel/models/groq_model.py
- camel/types/enums.py
- examples/models/groq_model_example.py
- examples/models/nvidia_model_example.py
Add llama3.3_70B model support.
`close #1302` 
> feat: Add llama3.3_70B model

- .gitignore
- camel/loaders/__init__.py
- camel/loaders/base_io.py
- camel/storages/object_storages/amazon_s3.py
- camel/storages/object_storages/azure_blob.py
- camel/storages/object_storages/google_cloud.py
- docs/key_modules/loaders.md
- poetry.lock
- pyproject.toml
- test/loaders/test_base_io.py
Updated the docs for `loaders` module. Also moved the static method in the Base IO file into module-level to improve the code quality.
> fix: outdated code snippets for loaders module in doc

- camel/toolkits/google_scholar_toolkit.py
- camel/utils/token_counting.py
set disallowed_special=() for openai tokencounter
> feat: openai tokencounter disallowed_special setting & google scholar proxy support

- CONTRIBUTING.md
add cookbook contribution guideline
> docs: add cookbook contribution guideline

- camel/models/openai_model.py
- poetry.lock
- pyproject.toml
`strict:ture` is  required by OpenAI beta client, otherwise would have error:
```
ValueError: `add` is not strict. Only `strict` function tools can be auto-parsed
```
but if adding `strict:ture` to OpenAI chat client,  for some cases would get error:
```
openai.BadRequestError: Error code: 400 - {'error': {'message': "Invalid schema for function 'tsp_dynamic_programming': In context=(), 'required' is required to be supplied and to be an array including every key in properties. Extra required key 'input_dataa' supplied.", 'type': 'invalid_request_error', 'param': 'tools[0].function.parameters', 'code': 'invalid_function_parameters'}}
```
You can use the syntax `close #15213` …
> fix: Remove strict:ture for OpenAI.chat.completions.create

- camel/messages/conversion/sharegpt/hermes/hermes_function_formatter.py
Small change to not lead with a new line when a hermes function call has no proceeding content.
Fixes https://github.com/camel-ai/camel/issues/1343 in CAMEL
> fix: Remove leading newlines from tool calls

- camel/benchmarks/__init__.py
- camel/benchmarks/apibank.py
- camel/benchmarks/apibench.py
- camel/benchmarks/gaia.py
- camel/benchmarks/nexus.py
- poetry.lock
- pyproject.toml
> fix: enhancment for tool benchmark integration

- CONTRIBUTING.md
Adds hint about installing from source, using a topic branch, and potentially adding extras with pip, relevant for developing cookbooks.
Minor change with no issue.
Motivation is that this is very helpful when developing cookbooks and many developers may not know Python has this functionality and that CAMEL supports it.
> Add hint about installing CAMEL from source / topic branch

- camel/toolkits/dappier_toolkit.py
- examples/toolkits/dappier_toolkit.py
> chore: docstring format dappier

- docs/conf.py
hot fix for cookbook url redirection
> fix: cookbook url for redirection

- docs/conf.py
- docs/key_modules/loaders.md
change the unstructured docs link
> chore:change the unstructured docs link

- README.md
Fix a few typos in README.md.
I am new to this exciting project and I want to make my first contribution by help polishing README, as mentioned in issue #1256.
> chore: fix a few typos in README.md

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- docs/conf.py
- docs/get_started/installation.md
- docs/key_modules/loaders.md
- pyproject.toml
> release: v0.2.17

- camel/messages/func_message.py
- camel/models/gemini_model.py
- test/messages/test_func_message.py
> fix: Gemini tool calling support

- camel/configs/internlm_config.py
- camel/messages/conversion/conversation_models.py
> chore: fix docstring and remove debug code

- camel/configs/deepseek_config.py
- camel/models/deepseek_model.py
- camel/types/enums.py
- docs/key_modules/models.md
- examples/models/deepseek_model_example.py
- test/models/test_deepseek_model.py
> feat:add deepseek_reasoner model

- camel/types/enums.py
> feat: Support SambaCloud and TogetherAI native tool call

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- docs/conf.py
- docs/cookbooks/data_generation/data_gen_with_real_function_calls_and_hermes_format.ipynb
- docs/cookbooks/data_generation/self_instruct_data_generation.ipynb
- docs/get_started/installation.md
- docs/key_modules/loaders.md
- pyproject.toml
> release: v0.2.18

- .env
- .github/workflows/build_package.yml
- .github/workflows/pytest_package.yml
- camel/embeddings/__init__.py
- camel/embeddings/jina_embedding.py
- camel/types/enums.py
- examples/embeddings/jina_embedding_example.py
- test/embeddings/test_jina_embedding.py
Integrate jina embedding
`close #1497` 
> feat: Integrate jina embedding

- camel/configs/gemini_config.py
- camel/configs/sglang_config.py
- camel/models/groq_model.py
- camel/types/enums.py
- examples/models/role_playing_with_groq.py
Adapt tool-calling capabilities from SGLang and Groq. Update the list of models supported by Groq and remove deprecated models
> feat: Support tool calling for SGLang and Groq

- docs/cookbooks/basic_concepts/create_your_first_agents_society.ipynb
Fixed a small typo a run into when reading the documentation
My motivation is to fix this typo and get used to this repository for further contributions
> docs: fixed a small typo

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/models/openai_model.py
- camel/types/enums.py
- camel/utils/token_counting.py
- docs/conf.py
- docs/get_started/installation.md
- docs/key_modules/loaders.md
- examples/models/openai_o1_example.py
- examples/models/openai_o3_mini_example.py
- pyproject.toml
> feat: Support OpenAI o3 mini

- camel/datahubs/huggingface.py
- camel/toolkits/search_toolkit.py
- test/datahubs/test_huggingface.py
- test/embeddings/test_open_source_embeddings.py
- test/embeddings/test_vlm_embeddings.py
We didn't get WolframAlpha result from all subpods before
> fix: WolframAlpha result from all subpods

- camel/types/enums.py
- docs/key_modules/models.md
- examples/models/gemini_model_example.py
- test/models/test_gemini_model.py
- test/models/test_zhipuai_model.py
GLM_4V_FLASH = "glm-4v-flash"
GLM_4V_PLUS_0111 = "glm-4v-plus-0111"
GLM_4_PLUS = "glm-4-plus"
GLM_4_AIR = "glm-4-air"
GLM_4_AIR_0111 = "glm-4-air-0111"
GLM_4_AIRX = "glm-4-airx"
GLM_4_LONG = "glm-4-long"
GLM_4_FLASHX = "glm-4-flashx"
GLM_4_FLASH = "glm-4-flash"
GLM_ZERO_PREVIEW = "glm-zero-preview"
GLM_3_TURBO = "glm-3-turbo"
GEMINI_2_0_FLASH = "gemini-2.0-flash-exp"
> chore: Update supported models

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/toolkits/semantic_scholar_toolkit.py
- camel/types/enums.py
- docs/conf.py
- docs/get_started/installation.md
- docs/key_modules/loaders.md
- pyproject.toml
- test/models/test_qwen_model.py
- test/toolkits/test_semantic_scholar_functions.py
> release: v0.2.20a0

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/types/enums.py
- docs/conf.py
- docs/get_started/installation.md
- docs/key_modules/loaders.md
- pyproject.toml
- test/models/test_qwen_model.py
> release: 0.2.20a1

- .github/PULL_REQUEST_TEMPLATE.md
- camel/benchmarks/ragbench.py
- poetry.lock
- pyproject.toml
1. remove ragas dependency
2. simplify PR template
> chore: Issue&PR template and dependency update

- docs/cookbooks/advanced_features/agents_with_tools.ipynb
Fix Unused Custom Tool in Tools Cookbook
close #1573 
> docs(cookbooks): Fix Unused Custom Tool in Tools Cookbook (issue-1573)

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- docs/conf.py
- docs/get_started/installation.md
- docs/key_modules/loaders.md
- pyproject.toml
> release: v0.2.20

- camel/utils/deduplication.py
- pyproject.toml
- test/utils/test_deduplication.py
enhance and refactor: https://github.com/camel-ai/camel/pull/1568
> refactor: Internal deduplication 

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- docs/conf.py
- docs/get_started/installation.md
- docs/key_modules/loaders.md
- poetry.lock
- pyproject.toml
update unstructured io version, nltk and libmagic dependency bug has been fixed in the new version
> chore: update unstructured io version

- camel/interpreters/subprocess_interpreter.py
- pyproject.toml
- test/prompts/test_prompt_base.py
In the interpreter toolkit, the code generated by the agent may not include print() statements, then there is no output from code execution available for the agent. Additionally, error information from the code execution is not passed back to the agent, preventing it from refining the generated code.
> fix: Subprocess interpreter don't have output

- camel/embeddings/openai_embedding.py
When initializing OpenAI, read the base_url parameter from the environment variable OPENAI_API_BASE_URL to ensure consistency with OpenAIModel and OpenAIAudioModels.
Fixes #1582 
> feat: URL Handling in OpenAIEmbedding to Align with OpenAIModel

- camel/interpreters/docker/Dockerfile
- camel/interpreters/docker_interpreter.py
- camel/interpreters/subprocess_interpreter.py
- camel/toolkits/sympy_toolkit.py
- docs/index.rst
- docs/key_modules/agents.md
- docs/key_modules/datagen.md
- examples/ai_society/babyagi_playing.py
- examples/bots/discord_bot.py
- examples/bots/discord_bot_use_msg_queue.py
- examples/bots/slack_bot.py
- examples/bots/slack_bot_use_msg_queue.py
- examples/models/role_playing_with_sambanova.py
- examples/structured_response/structure_response_prompt_engineering.py
- test/interpreters/test_docker_interpreter.py
- test/interpreters/test_subprocess_interpreter.py
- test/prompts/test_prompt_base.py
1. remove `message_window_size` setting in example code
2. add R language support in docker and subprocess interpreter
3. add documentation for `Agents` and `Data Generation`
4. add `compute_inner_product ` to sympy toolkit
5. fix subprocess interpreter `None` value output bug
> chore: Small enhancement and fix

- camel/agents/chat_agent.py
- camel/models/_utils.py
- camel/models/aiml_model.py
- camel/models/base_model.py
- camel/models/cohere_model.py
- camel/models/deepseek_model.py
- camel/models/gemini_model.py
- camel/models/internlm_model.py
- camel/models/mistral_model.py
- camel/models/moonshot_model.py
- camel/models/openai_model.py
- camel/models/qwen_model.py
- camel/models/siliconflow_model.py
- examples/toolkits/role_playing_with_functions.py
- test/models/test_model_factory.py
Issues based on review comment for ChatAgent refactor
> fix: Issues based on review comment for ChatAgent refactor

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/models/base_model.py
- camel/models/deepseek_model.py
- docs/conf.py
- docs/get_started/installation.md
- docs/key_modules/loaders.md
- pyproject.toml
- test/models/test_base_model.py
Remove <think> content in model request
> fix: Remove <think> content in model request

- camel/agents/knowledge_graph_agent.py
- examples/knowledge_graph/knowledge_graph_agent_example.py
> feat: custom prompt in graph agent

- camel/benchmarks/ragbench.py
- camel/toolkits/__init__.py
- camel/toolkits/networkx_toolkit.py
- poetry.lock
- pyproject.toml
- test/toolkits/test_networkx_toolkit.py
Enhancement PR for https://github.com/camel-ai/camel/pull/1456 based on review comment
> refactor: NetworkX integration

- camel/agents/_utils.py
- camel/models/_utils.py
- camel/models/aiml_model.py
- camel/models/groq_model.py
- camel/models/moonshot_model.py
- camel/models/ollama_model.py
- camel/models/qwen_model.py
Add support of tool calling and response format to more backend models, and resolve some leftover issues left in #1424.
This will close #1621.
> fix: Backend model tool call

- camel/models/base_model.py
- camel/utils/commons.py
- test/models/test_base_model.py
For the original thinking removing logic would get error it the message input is not string type
> fix: Base model handle image type

- test/models/test_anthropic_model.py
Update anthropic model unit test for refactored model backend
> test: Update anthropic model unit test for refactored model backend

- camel/datasets/base.py
- camel/environments/base.py
- camel/extractors/base.py
- camel/verifiers/base.py
CAMEL lacking standardized interface for core components of implementations for Loong:
Inconsistent implementations across different module
Difficulty in composing and mixing different components
Unclear boundaries between dataset management, environment control, and response extraction
Define clear, composable interfaces for core components:
Dataset management (BaseDataset)
Environment control (BaseEnvironment)
Response extraction (BaseExtractor)
Enable plug-and-play compatibility between different implementations
Provide robust error handling and state management
Support async operations for scalability
Implementing specific dataset loaders
Defining concrete reward functions
Implementing specific extractors for different formats
Handling model-specific optimizations
Implement three …
> feat: Initial implementation for env, dataset, extractor base model

- camel/types/enums.py
- docs/key_modules/models.md
- examples/models/openai_gpt_4.5_preview_example.py
- test/models/test_openai_model.py
add gpt-4.5-preview model https://platform.openai.com/docs/models#gpt-4-5
close #1671 
> feat:add gpt4.5 model

- camel/memories/agent_memories.py
- camel/memories/blocks/chat_history_block.py
- camel/memories/blocks/vectordb_block.py
- camel/memories/context_creators/score_based.py
- camel/memories/records.py
- test/loaders/test_pandaai.py
- test/memories/context_creators/test_score_based.py
- test/memories/test_blocks.py
- test/memories/test_vector_db_memory.py
In VectorDBBlock, each record is timestamped, and during the retrieval process, we prioritize sorting the records by these timestamps to ensure chronological order in the results.
- Added timestamp attribute in ContextRecord and MemoryRecord
- Changed sorting priority in ScoreBasedContextCreator to timestamp, score
- Adjusted some test cases to adapt to the change in priority
- Added test cases specifically for VectorDBMemory to determine if relevant historical messages can be recalled through classification questions and answers.
Fixes #1578 
> feat(memories): add timestamp in VectorDBMemory to prevent data retrieval order confusion

- test/models/test_cohere_model.py
> test: updated cohere test by adding async tests

- camel/datagen/self_improving_cot.py
Enhance JSON output with the ensure_ascii option in SelfImprovingCoTPipeline
Fixes #1717 
> feat(datagen): Enhance JSON output with ensure_ascii option in SelfImprovingCoTPipeline

- camel/toolkits/__init__.py
- camel/toolkits/video_analysis_toolkit.py
- camel/toolkits/video_download_toolkit.py
- pyproject.toml
- test/toolkits/test_video_function.py
> feat: Add video analysis toolkit

- .container/Dockerfile
- .container/minimal_build/Dockerfile
- .github/actions/camel_install/action.yml
- .github/workflows/build_package.yml
- .github/workflows/publish_release.yml
- .github/workflows/pytest_apps.yml
- .github/workflows/pytest_package.yml
- CONTRIBUTING.md
- docs/get_started/installation.md
> chore: Update uv install

- camel/toolkits/__init__.py
- camel/toolkits/audio_analysis_toolkit.py
- test/toolkits/test_audio_analysis_toolkit.py
> refactor: Audio analysis toolkit

- camel/toolkits/image_analysis_toolkit.py
> fix: issues about local image path

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- docs/conf.py
- docs/key_modules/loaders.md
- pyproject.toml
- uv.lock
> release: version 0.2.23

- camel/toolkits/__init__.py
- camel/toolkits/terminal_toolkit.py
- docs/key_modules/tools.md
- examples/toolkits/terminal_toolkit.py
- test/toolkits/test_terminal_toolkit.py
> feat: Terminal Toolkit

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/societies/role_playing.py
- docs/conf.py
- docs/key_modules/loaders.md
- pyproject.toml
- test/agents/test_role_playing.py
- uv.lock
RolePlaying support async run
release camel 0.2.24
> feat: RolePlaying support async run

- camel/environments/base.py
- camel/extractors/__init__.py
- camel/extractors/base.py
- camel/extractors/python_strategies.py
- examples/extractors/python_strategies_example.py
- test/extractors/test_base_extractor.py
- test/extractors/test_python_strategies.py
Update base and python extractor based one code view comment: https://github.com/camel-ai/camel/pull/1742#pullrequestreview-2675434124
> refactor: Update base and python extractor

- camel/datasets/base.py
Updat base dataset PR based on code review comment: https://github.com/camel-ai/camel/pull/1734#pullrequestreview-2675603596
> refactor: Updat base dataset PR

- camel/toolkits/terminal_toolkit.py
fix file_find_by_name function
> fix:terminal_toolkit windows

- camel/toolkits/__init__.py
- camel/toolkits/pubmed_toolkit.py
- examples/toolkits/pubmed_toolkit.py
- test/toolkits/test_pubmed_toolkit.py
> fead: Add pubmed in toolkits

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- docs/conf.py
- docs/key_modules/loaders.md
- pyproject.toml
- uv.lock
> release: version 0.2.26

- camel/toolkits/web_toolkit.py
> fix: playwright already stopped in web toolkit

- .env
- camel/toolkits/search_toolkit.py
- examples/toolkits/search_toolkit.py
- test/toolkits/test_search_functions.py
> feat: Add bocha search in search toolkit

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/workflows/build_package.yml
- .github/workflows/pytest_package.yml
- camel/__init__.py
- camel/models/volcano_model.py
- camel/toolkits/__init__.py
- camel/toolkits/browser_toolkit.py
- camel/toolkits/search_toolkit.py
- camel/types/enums.py
- docs/conf.py
- docs/key_modules/loaders.md
- docs/key_modules/tools.md
- examples/models/role_playing_with_volcano.py
- examples/models/volcano_model_example.py
- examples/toolkits/search_toolkit.py
- examples/toolkits/web_toolkit.py
- pyproject.toml
- test/models/test_volcano_model.py
- uv.lock
enhance new feature implementation
> fix: enhance new feature implementation

- camel/models/vllm_model.py
> bug fix: vllm can't do tool call

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- docs/conf.py
- docs/key_modules/loaders.md
- pyproject.toml
- uv.lock
> release: 0.2.28

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/agents/chat_agent.py
- docs/conf.py
- docs/key_modules/loaders.md
- pyproject.toml
- uv.lock
add Agent tool call try expect
suggestion from https://github.com/camel-ai/owl/issues/253#issuecomment-2720348548
optimize logger info for image as suggested in https://github.com/camel-ai/owl/issues/277 
> feat: Agent tool call try expect, update image log

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- docs/conf.py
- docs/key_modules/loaders.md
- pyproject.toml
- uv.lock
> release: v 0.2.30

- camel/toolkits/search_toolkit.py
- examples/toolkits/search_toolkit.py
- test/toolkits/test_search_functions.py
> feat: add bing search

- docs/key_modules/models.md
You are using the wrong link to refer to the supported models by SambaNova. I have updated it here. 
https://docs.sambanova.ai/cloud/docs/get-started/supported-models
> Corrected SambaNova Models link

- docs/key_modules/agents.md
Fixed an outdated import in the docs
> fix outdated docs in key modules

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/agents/chat_agent.py
- docs/conf.py
- docs/key_modules/loaders.md
- pyproject.toml
- uv.lock
> release: version 0.2.32, revert KnowNo

- docs/key_modules/agents.md
- pyproject.toml
- uv.lock
Shrink down unsused dependencies from the toml.
Links #1867
> shrink down deps

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- docs/conf.py
- docs/key_modules/loaders.md
- pyproject.toml
- uv.lock
> release: 0.2.33

- test/models/test_nvidia_model.py
> test: updated nvidia model tests with async run

- test/models/test_gemini_model.py
> test: updated gemini model tests to add async run

- README.md
Just fixing 2 typos in README.md: see commit diff for details.
- [ X] I have read the [CONTRIBUTION](https://github.com/camel-ai/camel/blob/master/CONTRIBUTING.md) guide (**required**)
- [X ] I have updated the documentation if needed:
> fix: 2 typos in README.md

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/agents/knowledge_graph_agent.py
- docs/conf.py
- docs/key_modules/loaders.md
- pyproject.toml
- uv.lock
> release: version 0.2.34

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/agents/_types.py
- camel/agents/_utils.py
- camel/agents/chat_agent.py
- camel/configs/openai_config.py
- docs/conf.py
- docs/key_modules/loaders.md
- pyproject.toml
- test/agents/test_chat_agent.py
- uv.lock
> fix: Record all tool calls from LLM response

- camel/models/stub_model.py
- camel/retrievers/vector_retriever.py
- camel/utils/chunker/__init__.py
- camel/utils/chunker/code_chunker.py
- camel/utils/chunker/uio_chunker.py
- camel/utils/token_counting.py
> enhance: chunker module (PR 1727)

- docs/key_modules/tools.md
This PR adds the missing toolkits in the docs.
> docs: update latest docs with missing toolkits

- camel/toolkits/mcp_toolkit.py
> feat: accepting header in mcp toolkits

- .github/workflows/build_package.yml
- .github/workflows/pytest_package.yml
- camel/memories/agent_memories.py
- camel/memories/blocks/chat_history_block.py
- camel/storages/key_value_storages/mem0_cloud.py
- pyproject.toml
- test/storages/key_value_storages/test_mem0_cloud.py
- test/toolkits/test_code_execution.py
- test/toolkits/test_mcp_toolkit.py
> fix: mem0 mypy test and doc, openrouter key, mcp test

- camel/models/gemini_model.py
> fix: remove anyOf to support Gemini tool call

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- docs/conf.py
- docs/key_modules/loaders.md
- pyproject.toml
- uv.lock
> release: v 0.2.36

- camel/datasets/static_dataset.py
- camel/environments/single_step.py
- camel/extractors/__init__.py
- camel/verifiers/python_verifier.py
> enhance: Add cookbook for how to use SingleStepEnv PR1922

- camel/environments/single_step.py
- camel/verifiers/python_verifier.py
- docs/cookbooks/loong/batched_single_step_env.ipynb
- docs/cookbooks/loong/single_step_env.ipynb
This PR will add a few cookbooks for the Loong project showing
- how to use the single-step RL environment `SingleStepEnv`
- how to use the single-step RL environment `SingleStepEnv` for batched envs
> docs: improve cookbook for SingleStepEnv and add cookbook for batched SingleStepEnv

- README.md
> Fix typo of links on readme

- camel/agents/repo_agent.py
- test/agents/test_repo_agent.py
> enhance: Repo agent PR 1941

- camel/verifiers/python_verifier.py
> ehance: python verifier on windows PR 2005

- docs/cookbooks/basic_concepts/create_your_first_agents_society.ipynb
This a repetition fixing https://github.com/camel-ai/camel/pull/1965#issuecomment-2754198046 where all lines seemed to be changed whereas only 2 typos are fixed by this PR
- [ X] I have read the [CONTRIBUTION](https://github.com/camel-ai/camel/blob/master/CONTRIBUTING.md) guide (**required**)
- [X ] I have updated the documentation if needed:
> fix create_your_first_agents_society.ipynb: 2 typos

- camel/storages/vectordb_storages/tidb.py
- uv.lock
> chore: Enhance TiDB vector DB integration

- camel/toolkits/__init__.py
- camel/toolkits/browser_toolkit.py
- examples/toolkits/web_toolkit.py
- test/toolkits/test_browser_toolkit.py
It supports running browsers like Chrome, Chrome, and Edge. Add test suite for browser toolkit.
> feat: Support browser toolkit with pre-defined dynamic channel

- camel/toolkits/__init__.py
- camel/toolkits/browser_toolkit.py
- examples/toolkits/browser_toolkit.py
- test/toolkits/test_browser_toolkit.py
> enhance: Support browser toolkit with dynamic channel  PR 1937

- camel/toolkits/__init__.py
- camel/toolkits/searxng_toolkit.py
- examples/toolkits/searxng_toolkit_example.py
> enhance: Searxng integration PR 1963

- camel/memories/context_creators/score_based.py
> enhance: memory sort without system message #1788

- camel/interpreters/docker_interpreter.py
- camel/interpreters/e2b_interpreter.py
- camel/interpreters/subprocess_interpreter.py
> fix:SubprocessInterpreter does not successfully provide code

- camel/agents/mcp_agent.py
- camel/toolkits/mcp_toolkit.py
- examples/agent/mcp/mcp_agent.py
- examples/agent/mcp/mcp_servers_config.json
- test/agents/test_mcp_agent.py
> enhance: enable MCP to models without function calling ability #1978

- camel/toolkits/terminal_toolkit.py
- examples/toolkits/terminal_toolkit.py
> enhance: terminal toolkit PR 1846

- camel/datasets/few_shot_generator.py
- camel/datasets/self_instruct_generator.py
- camel/environments/single_step.py
- camel/verifiers/base.py
- camel/verifiers/math_verifier.py
- camel/verifiers/python_verifier.py
- examples/verifier/math_verifier_example.py
- examples/verifier/python_verifier_example.py
- test/environments/test_single_stage_env.py
- test/verifiers/test_base_verifier.py
- test/verifiers/test_python_verifier.py
> fix: rename 'ground_truth' in verifier to 'reference_answer'

- camel/datasets/base_generator.py
- test/environments/test_single_stage_env.py
> fix: change name from puffer to buffer in single step env

- .github/workflows/build_package.yml
- .github/workflows/pytest_package.yml
- camel/toolkits/meshy_toolkit.py
> chore: fix cicd

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/environments/single_step.py
- camel/utils/chunker/code_chunker.py
- docs/conf.py
- docs/key_modules/loaders.md
- pyproject.toml
- uv.lock
> release: 0.2.39

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/utils/chunker/code_chunker.py
- camel/utils/chunker/uio_chunker.py
- docs/conf.py
- docs/key_modules/loaders.md
- pyproject.toml
- uv.lock
> release: v 0.2.40

- camel/datasets/few_shot_generator.py
> chore: add time out to few shot generator

- camel/models/vllm_model.py
> fix: Vllm tool call schema remove additionalProperties

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/agents/chat_agent.py
- docs/conf.py
- docs/key_modules/loaders.md
- pyproject.toml
- uv.lock
> fix: enhance timestamp for agent memory update

- camel/models/vllm_model.py
> chore: update vllm implementation

- camel/verifiers/python_verifier.py
- test/verifiers/test_python_verifier.py
> update: add float type comparison

- camel/types/enums.py
- examples/models/openrouter_llama3.1_example .py
- examples/models/openrouter_llama4_example.py
- examples/models/openrouter_model_example.py
Adding llama4 model in the enum and examples with openrouter provider.
Links #2117
> feat: llama4 support in openrouter

- camel/societies/workforce/workforce.py
polish docstring and add warning message to workforce default model setting
> chore: add warning message to workforce default model setting

- docs/cookbooks/loong/multi_step_rl.ipynb
I added some comments to the cookbook so it is more accessible.
> docs: improve cookbook for Tic Tac Toe

- camel/embeddings/__init__.py
- camel/embeddings/together_embedding.py
- camel/toolkits/google_calendar_toolkit.py
- examples/embeddings/together_embedding_example.py
> feat: add together embedding

- camel/runtime/ubuntu_docker_runtime.py
- examples/runtime/ubuntu_docker_runtime/Dockerfile
- examples/runtime/ubuntu_docker_runtime/manage_camel_docker.sh
- examples/runtime/ubuntu_docker_runtime/ubuntu_docker_example.py
> enhance:Add Ubuntu docker runtime PR 1952

- .github/workflows/build_package.yml
- .github/workflows/pytest_package.yml
- camel/configs/ppio_config.py
- camel/configs/reka_config.py
- camel/configs/samba_config.py
- camel/configs/togetherai_config.py
- camel/models/ppio_model.py
> fix: ppo model platform integration

- camel/datasets/few_shot_generator.py
- camel/environments/single_step.py
- examples/dataset/few_shot_generator.py
> fix: capture shots in `FewShotGenerator` in metadata

- camel/models/togetherai_model.py
- camel/toolkits/browser_toolkit.py
- camel/types/enums.py
- examples/models/togetherai_model_example.py
Update Together AI using beta client for structured output & support llama4
> refactor: Together AI using beta client for structured output & support llama4

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- docs/conf.py
- docs/key_modules/loaders.md
- pyproject.toml
- uv.lock
> release: v 0.2.44

- camel/toolkits/browser_toolkit.py
> fix: circular import

- camel/toolkits/audio_analysis_toolkit.py
- camel/toolkits/dalle_toolkit.py
- camel/toolkits/excel_toolkit.py
- camel/toolkits/image_analysis_toolkit.py
- camel/toolkits/networkx_toolkit.py
- camel/toolkits/openai_agent_toolkit.py
- camel/toolkits/searxng_toolkit.py
- camel/toolkits/slack_toolkit.py
- camel/toolkits/video_analysis_toolkit.py
- camel/toolkits/weather_toolkit.py
- camel/toolkits/zapier_toolkit.py
adding missing timeout in toolkits
> chore: adding missing timeout in toolkits

- README.md
- camel/toolkits/audio_analysis_toolkit.py
Fix the outdated links in the readme for cookbooks
> fix: outdated links

- camel/models/cohere_model.py
- camel/models/litellm_model.py
- camel/models/mistral_model.py
- camel/models/reka_model.py
- camel/models/volcano_model.py
> chore: add timeout setting for all model backend

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- docs/conf.py
- docs/key_modules/loaders.md
- pyproject.toml
- uv.lock
> release: v 0.2.45

- camel/models/aiml_model.py
- camel/models/anthropic_model.py
- camel/models/deepseek_model.py
- camel/models/gemini_model.py
- camel/models/groq_model.py
- camel/models/internlm_model.py
- camel/models/modelscope_model.py
- camel/models/moonshot_model.py
- camel/models/nemotron_model.py
- camel/models/nvidia_model.py
- camel/models/ollama_model.py
- camel/models/openai_compatible_model.py
- camel/models/openrouter_model.py
- camel/models/ppio_model.py
- camel/models/qwen_model.py
- camel/models/reka_model.py
- camel/models/siliconflow_model.py
- camel/models/togetherai_model.py
- camel/models/vllm_model.py
- camel/models/volcano_model.py
- camel/models/yi_model.py
- camel/models/zhipuai_model.py
fix:https://github.com/camel-ai/camel/issues/2164
> feat:Update all model implementation  by inheriting from OpenAICompatibleModel

- camel/toolkits/video_analysis_toolkit.py
- uv.lock
https://github.com/camel-ai/camel/pull/1852#pullrequestreview-2780113536
> enhance: video toolkit refator PR #1852

- docs/key_modules/models.md
Forgot to add lmstudio in the docs section.
> chore: adding lmstudio to docs

- camel/models/groq_model.py
- camel/models/openai_compatible_model.py
- camel/models/openrouter_model.py
- camel/models/qwen_model.py
- examples/models/openai_compatibility_model_examples/zhipu_response_format.py
When using `response_format` some model interfaces do not support the current implementation of `request_parse` in OpenAICompatibleModel. To address this, I've made some enhancements and updated several models.
> feat: Enhance OpenAICompatibleModel

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/configs/qwen_config.py
- docs/conf.py
- docs/cookbooks/loong/batched_single_step_env.ipynb
- docs/cookbooks/loong/multi_step_rl.ipynb
- docs/cookbooks/loong/single_step_env.ipynb
- docs/key_modules/loaders.md
- pyproject.toml
- uv.lock
> fix: Qwen config extra_body type

- README.md
> docs: Add PyPI download badge to README

- README.md
> [README] Add trending badge

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/datasets/few_shot_generator.py
- camel/datasets/models.py
- camel/models/openai_model.py
- camel/toolkits/browser_toolkit.py
- camel/types/enums.py
- camel/utils/token_counting.py
- docs/conf.py
- docs/key_modules/loaders.md
- pyproject.toml
- test/datasets/test_base_dataset.py
- test/models/test_openai_model.py
- uv.lock
> chore: Support O4-mini, O3, fix FewShotGenerator bug, update browser toolkit

- camel/storages/vectordb_storages/oceanbase.py
- pyproject.toml
- test/storages/vector_storages/test_oceanbase.py
- uv.lock
enhance based on review comment: https://github.com/camel-ai/camel/pull/2244#pullrequestreview-2783810275
> enhance: Integrate Oceanbase database #2244

- camel/toolkits/jina_reranker_toolkit.py
- examples/toolkits/jina_reranker_toolkit.py
- test/toolkits/test_jina_reranker_toolkit.py
enhancement based on review comment:https://github.com/camel-ai/camel/pull/2170#pullrequestreview-2785082808
> enhance: jina reranker toolkit PR 2170

- camel/toolkits/__init__.py
- camel/toolkits/jina_reranker_toolkit.py
- docs/key_modules/tools.md
- examples/toolkits/jina_reranker_toolkit.py
- test/toolkits/test_jina_reranker_toolkit.py
Adding support for jina reranker toolkit
Links #2161
> feat: Jina reranker toolkit

- camel/toolkits/search_toolkit.py
- examples/toolkits/search_toolkit.py
- test/toolkits/test_jina_reranker_toolkit.py
- test/toolkits/test_search_functions.py
> enhance: Add Alibaba Tongxiao Search API Support PR #2127

- camel/loaders/scrapegraph_reader.py
- examples/loaders/scrapegraph_example.py
- pyproject.toml
- test/loaders/test_scrapegraph_reader.py
Reference: [https://github.com/camel-ai/camel/issues/2207](url)
> feat: add scrapegraph-sdk integration

- camel/loaders/__init__.py
- camel/loaders/scrapegraph_reader.py
- examples/loaders/scrapegraph_example.py
- pyproject.toml
- test/loaders/test_scrapegraph_reader.py
- uv.lock
> enhance: add scrapegraph-sdk integration PR2206

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/agents/chat_agent.py
- camel/toolkits/dalle_toolkit.py
- docs/conf.py
- docs/key_modules/loaders.md
- pyproject.toml
- test/agents/test_chat_agent.py
- test/toolkits/test_dalle_functions.py
- uv.lock
When running astep in ChatAgent, external tool call will be executed, instead of directly returning
> fix: ChatAgent astep bug

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/societies/workforce/role_playing_worker.py
- camel/societies/workforce/single_agent_worker.py
- docs/conf.py
- docs/key_modules/loaders.md
- examples/workforce/hackathon_judges.py
- pyproject.toml
- test/storages/vector_storages/test_milvus.py
- uv.lock
> chore: fix pre commit, release new version

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/configs/modelscope_config.py
- camel/models/modelscope_model.py
- camel/types/enums.py
- docs/conf.py
- docs/key_modules/loaders.md
- examples/models/modelscope_model_example.py
- pyproject.toml
- uv.lock
> feat: Support Qwen 3 in modelscope

- camel/verifiers/__init__.py
- camel/verifiers/physics_verifier.py
- camel/verifiers/python_verifier.py
- examples/verifier/physics_verifier_example.py
- pyproject.toml
> enhance: Physics verifier PR2138

- camel/agents/chat_agent.py
- test/agents/test_chat_agent.py
update based on comment https://github.com/camel-ai/camel/pull/1699#pullrequestreview-2805705727
> enhance: simplify creating agent using str, add examples PR1699

- .github/workflows/build_package.yml
> chore: update build yml file setting

- camel/models/azure_openai_model.py
> chore: Azure OpenAI support azure_ad_token_provider

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/models/ollama_model.py
- camel/models/vllm_model.py
- docs/conf.py
- docs/key_modules/loaders.md
- pyproject.toml
- uv.lock
> fix: Ollama and VLLM api key & url setting

- .env
- camel/toolkits/__init__.py
- camel/toolkits/klavis_toolkit.py
- camel/utils/commons.py
- docs/key_modules/tools.md
- examples/toolkits/klavis_toolkit.py
- test/toolkits/test_klavis_toolkit.py
Adding Klavis AI toolkit. Klavis AI is working on MCP integrations for AI applications. For more details, visit https://www.klavis.ai.
I have tested the added example and it is working correctly.
> feat: Add Klavis toolkit.

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- docs/conf.py
- docs/key_modules/loaders.md
- pyproject.toml
- uv.lock
> release: v0.2.52

- camel/models/model_factory.py
- camel/toolkits/function_tool.py
> feat: ModelFactory support passing additional argument

- camel/embeddings/gemini_embedding.py
- camel/embeddings/openai_embedding.py
- camel/embeddings/together_embedding.py
- camel/types/enums.py
- docs/key_modules/embeddings.md
- examples/embeddings/gemini_embedding_example.py
- pyproject.toml
- uv.lock
based on review comment: https://github.com/camel-ai/camel/pull/2325#pullrequestreview-2813553250
> enhance: gemini embedding support. PR2325

- camel/embeddings/__init__.py
- camel/embeddings/gemini_embedding.py
- camel/embeddings/openai_embedding.py
- camel/embeddings/together_embedding.py
- camel/types/__init__.py
- camel/types/enums.py
- docs/key_modules/embeddings.md
- examples/embeddings/gemini_embedding_example.py
- pyproject.toml
- test/embeddings/test_gemini_embedding.py
- uv.lock
Refer to https://github.com/camel-ai/camel/issues/1816.
> feat: gemini embedding support.

- camel/utils/mcp.py
Fix https://github.com/camel-ai/camel/issues/2321
> docs: Add docstring for MCPServer

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- docs/conf.py
- docs/key_modules/loaders.md
- examples/test/test_single_agent.py
- pyproject.toml
- test/agents/test_chat_agent.py
- test/toolkits/test_aci_toolkit.py
- uv.lock
> release: fix unit test and release 0.2.53

- .gitignore
- camel/agents/__init__.py
- camel/agents/mcp_agent.py
- camel/toolkits/mcp_toolkit.py
- examples/agents/mcp_agent/calculator_server.py
- examples/agents/mcp_agent/mcp_agent.py
- examples/agents/mcp_agent/mcp_servers_config.json
> enhance: enable MCP to models without function calling PR2128

- camel/utils/__init__.py
- camel/utils/commons.py
- examples/toolkits/browser_toolkit_with_cookie.py
> chore: move browser_toolkit_save_auth_cookie to utils

- camel/toolkits/klavis_toolkit.py
- test/toolkits/test_klavis_toolkit.py
Following up the comment https://github.com/camel-ai/camel/pull/2309#issuecomment-2848775321 to add list tools and call tool functions.
> Add list tools and call tool functions for Klavis AI toolkit.

- camel/models/mistral_model.py
> feat: mistral model add async implementation

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/models/gemini_model.py
- docs/conf.py
- docs/key_modules/loaders.md
- pyproject.toml
- uv.lock
> chore: add error rasing for gemini tool call with response format

- camel/loaders/__init__.py
- camel/loaders/markitdown.py
- docs/key_modules/loaders.md
- examples/loaders/markitdown_example.py
- examples/loaders/mineru_example.py
- examples/loaders/pandas_example.py
- pyproject.toml
- test/loaders/test_markitdown.py
- uv.lock
> enhance: markitdown loader PR2248

- pyproject.toml
> fix: delete reduplicative package

- camel/toolkits/base.py
- docs/key_modules/tools.md
- examples/mcp_arxiv_toolkit/arxiv_toolkit_server.py
mcp server launch with better interface
Fixes #2320
> feat: mcp server launch with better interface

- .gitignore
- camel/toolkits/base.py
- camel/toolkits/mcp_toolkit.py
- docs/key_modules/tools.md
- examples/mcp_arxiv_toolkit/arxiv_toolkit_server.py
- test/utils/test_mcp_server.py
> chore: update mcp usage in test,support all connection modes

- CONTRIBUTING.md
- test/conftest.py
docs: clarify use of .env and automatic loading in pytest
- Mention that `.env` file already exists at the repo root
- Instruct users to add keys to it instead of creating a new file
- Clarify that `conftest.py` automatically loads `.env`, so tests can be run directly with `pytest .`
> docs: clarify use of .env and automatic loading in pytest

- camel/societies/workforce/workforce.py
> chore: update workforce default tool for new agent

- camel/toolkits/excel_toolkit.py
> fix: wrong docstring in excel_toolkit.py

- camel/agents/mcp_agent.py
- examples/agents/mcp_agent/mcp_agent_using_registry.py
> enhance: add MCP search agent PR2222

- camel/agents/chat_agent.py
- camel/agents/critic_agent.py
- camel/benchmarks/browsecomp.py
- camel/societies/role_playing.py
- camel/societies/workforce/role_playing_worker.py
- camel/societies/workforce/workforce.py
> enhance: Integrating BrowseComp Benchmark PR2293

- docs/cookbooks/advanced_features/agents_with_MCP.ipynb
I have learned a lot from the great agent_with_MCP cookbook by @MuggleJinx.
I found a few typos in the cookbook and have corrected them. 
I do not have write access to the colab, so I did not change the colab version. I am happy to help edit the colab version as well, if necessary.
> chore: fixed typos in and edited agents_with_MCP cookbook

- docs/key_modules/tools.md
- examples/mcp_arxiv_toolkit/arxiv_toolkit_server.py
> fix: mcp arxiv toolkit

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/agents/chat_agent.py
- docs/conf.py
- docs/key_modules/loaders.md
- pyproject.toml
- uv.lock
> fix: Multi-round step running token count in ChatAgent

- camel/toolkits/mcp_toolkit.py
Close OWL[#520](https://github.com/camel-ai/owl/issues/520). 
> fix: Run mcp sse connection

- camel/toolkits/mcp_toolkit.py
- test/toolkits/test_mcp_toolkit.py
> fix: mcp toolit and test

- docs/cookbooks/advanced_features/agents_with_tools_from_ACI.ipynb
- docs/cookbooks/advanced_features/index.rst
> docs: Add ACI usage cookbook

- camel/toolkits/wolfram_alpha_toolkit.py
- docs/cookbooks/advanced_features/agents_with_tools_from_ACI.ipynb
- examples/toolkits/wolfram_alpha_toolkit.py
> chore: minor fix for aci cookbook and wolframaplha integration

- examples/runtime/remote_http_runtime.py
When writing document for Runtime module, I find a minor bug in the example for `remote_http_runtime.py`. I have fixed it.
**Root cause**: The MathToolkit has been updated, with more tools being integrated.
> fix: minor bug in http runtime example

- camel/toolkits/mcp_toolkit.py
- examples/mcp_arxiv_toolkit/mcp_servers_config.json
> feat: streamable HTTP

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/toolkits/github_toolkit.py
- camel/toolkits/wolfram_alpha_toolkit.py
- docs/conf.py
- docs/key_modules/loaders.md
- examples/toolkits/github_toolkit.py
- examples/toolkits/wolfram_alpha_toolkit.py
- pyproject.toml
- test/toolkits/test_github_toolkit.py
- test/toolkits/test_wolframalpha_toolkit.py
- uv.lock
refactor Wolfram Alpha Toolkit make step by step api as separated function, also update example code
refactor Github Toolkit move the repo name setting from `__init__` to each functions
> refactor: Wolfram Alpha and Github Toolkit

- examples/workforce/role_playing_with_agents.py
this will fix https://github.com/camel-ai/camel/issues/2452
[BUG] example of workforce report "TypeError: 'int' object does not support item assignment"
> fix: example of workforce bug

- camel/storages/__init__.py
- camel/storages/vectordb_storages/__init__.py
- camel/storages/vectordb_storages/faiss.py
- pyproject.toml
- test/storages/vector_storages/test_faiss.py
- uv.lock
> enhance: Add new vector storage db FAISS PR2034

- camel/configs/anthropic_config.py
- camel/types/enums.py
- examples/models/anthiropic_model_example.py
> feat: Support Claude 4

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/agents/chat_agent.py
- camel/models/model_manager.py
- camel/toolkits/bohrium_toolkit.py
- docs/conf.py
- docs/key_modules/loaders.md
- docs/mintlify/convert_notebook2mdx.py
- docs/mintlify/key_modules/loaders.mdx
- docs/mintlify/reference/camel.agents.chat_agent.mdx
- docs/mintlify/reference/camel.toolkits.bohrium_toolkit.mdx
- examples/agent/agents_share_modelmanager.py
- pyproject.toml
- test/toolkits/test_bohrium_toolkit.py
- uv.lock
To make different `ChatAgent` could share the same `ModelManager`.
Also add a lock to fix the `ModelManager`'s coroutine safe.
> `ChatAgent` is able to accept a `ModelManager` as model's input.

- camel/loaders/__init__.py
- camel/loaders/chunkr_reader.py
- docs/key_modules/loaders.md
- docs/mintlify/key_modules/loaders.mdx
- docs/mintlify/reference/camel.loaders.chunkr_reader.mdx
- pyproject.toml
- uv.lock
> enhance: update Chunkr integration by Chunkr SDK PR1779

- docs/key_modules/agents.md
- docs/key_modules/datagen.md
- docs/key_modules/embeddings.md
- docs/key_modules/interpreters.md
- docs/key_modules/loaders.md
- docs/key_modules/memory.md
- docs/key_modules/messages.md
- docs/key_modules/models.md
- docs/key_modules/prompts.md
- docs/key_modules/retrievers.md
- docs/key_modules/runtimes.md
- docs/key_modules/society.md
- docs/key_modules/storages.md
- docs/key_modules/tasks.md
- docs/key_modules/tools.md
- docs/key_modules/workforce.md
- docs/mintlify/docs.json
> docs: Fix the indentation and list all key modules

- camel/societies/workforce/workforce.py
- docs/mintlify/docs.json
- docs/mintlify/reference/camel.loaders.mistral_reader.mdx
- docs/mintlify/reference/camel.societies.workforce.workforce.mdx
The workforce documentation had minimal explanation of customizing the coordinator and task agents. Enhanced the workforce docstring, added an example, and improved the warning messages. Part of #2486.
> enhance: Workforce Docstring

- camel/toolkits/pptx_toolkit.py
- examples/toolkits/pptx_toolkit.py
- test/toolkits/test_pptx_toolkit.py
> enhance: Minor update to the pptx_filewrite PR2475

- docs/key_modules/interpreters.md
> docs: add doc for interpreter module

- docs/cookbooks/mcp/agents_with_sql_mcp.ipynb
changes in cookbook sql from tools.connection() method to tools.connect() with disconnect() method
> docs: minor update on cookbook sql

- camel/toolkits/mcp_toolkit.py
- camel/utils/mcp_client.py
- docs/mintlify/reference/camel.toolkits.mcp_toolkit.mdx
- docs/mintlify/reference/camel.utils.mcp_client.mdx
> enhance: Enhance the support of running mcp in sync mode PR2575

- camel/types/enums.py
- docs/key_modules/models.md
- examples/models/mistral_model_example.py
- test/models/test_mistral_model.py
> feat: add Magistral Medium (magistral-medium-2506) model support

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/agents/chat_agent.py
- docs/conf.py
- pyproject.toml
- uv.lock
> fix:ChatAgent get_available_tools tool errors

- camel/tasks/task.py
- camel/toolkits/task_planning_toolkit.py
- examples/toolkits/task_planning_toolkit.py
> enhance: Task planning toolkit PR2535

- camel/agents/chat_agent.py
> feat: Replace ChatAgent single_iteration with max_iteration_

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/environments/rlcards_env.py
- camel/societies/workforce/prompts.py
- camel/societies/workforce/single_agent_worker.py
- camel/societies/workforce/task_channel.py
- camel/societies/workforce/worker.py
- camel/societies/workforce/workforce.py
- docs/conf.py
- examples/workforce/eigent.py
- pyproject.toml
- uv.lock
> feat: Workforce support parallelization to further improve efficiency

- camel/datagen/self_improving_cot.py
- camel/runtimes/configs.py
- camel/runtimes/daytona_runtime.py
- camel/runtimes/docker_runtime.py
- camel/runtimes/remote_http_runtime.py
- camel/societies/workforce/prompts.py
- camel/societies/workforce/single_agent_worker.py
- camel/societies/workforce/utils.py
- camel/societies/workforce/worker.py
- camel/societies/workforce/workforce.py
- camel/tasks/task.py
- camel/toolkits/aci_toolkit.py
- camel/toolkits/arxiv_toolkit.py
- camel/toolkits/dappier_toolkit.py
- camel/toolkits/file_write_toolkit.py
- camel/toolkits/github_toolkit.py
- camel/toolkits/pptx_toolkit.py
- camel/toolkits/sympy_toolkit.py
- camel/toolkits/task_planning_toolkit.py
- camel/toolkits/thinking_toolkit.py
- examples/workforce/eigent.py
> feat: Workforce enhancement

- camel/toolkits/__init__.py
- camel/toolkits/non_visual_browser_toolkit/actions.py
- camel/toolkits/non_visual_browser_toolkit/agent.py
- camel/toolkits/non_visual_browser_toolkit/browser_non_visual_toolkit.py
- camel/toolkits/non_visual_browser_toolkit/nv_browser_session.py
- camel/toolkits/non_visual_browser_toolkit/snapshot.js
- camel/toolkits/non_visual_browser_toolkit/snapshot.py
- examples/toolkits/browser_non_visual_toolkit_example.py
- examples/workforce/eigent.py
> enhance: initial enhance for non visual browser method PR2674

- camel/toolkits/video_analysis_toolkit.py
- pyproject.toml
- uv.lock
> enhance: Update OCR capability to  video_analysis_toolkit.py PR2660

- camel/agents/chat_agent.py
> chore: update chatagent clone to avoid sharing state

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/toolkits/non_visual_browser_toolkit/browser_non_visual_toolkit.py
- camel/toolkits/non_visual_browser_toolkit/nv_browser_session.py
- camel/toolkits/non_visual_browser_toolkit/snapshot.py
- docs/conf.py
- examples/toolkits/browser_non_visual_toolkit_example.py
- examples/workforce/eigent.py
- pyproject.toml
- uv.lock
> chore: enhance non visual browser

- camel/toolkits/__init__.py
- camel/toolkits/edgeone_pages_mcp_toolkit.py
- camel/toolkits/non_visual_browser_toolkit/browser_non_visual_toolkit.py
- examples/toolkits/browser_non_visual_toolkit_example.py
- examples/toolkits/edgeone_pages_mcp_toolkit.py
- examples/workforce/eigent.py
> feat: update browser_nonvisual_human_in_the_loop and EdgeOnePagesMCPToolkit

- camel/toolkits/__init__.py
- camel/toolkits/craw4ai_toolkit.py
- camel/toolkits/markitdown_toolkit.py
- examples/workforce/eigent.py
> feat: set craw4ai and markitdown as toolkit

- camel/storages/vectordb_storages/chroma.py
> chore: update chormadb

- camel/toolkits/excel_toolkit.py
- test/toolkits/test_excel_toolkit.py
> enhance: Enhance_excel_toolkit PR2687

- camel/types/enums.py
- docs/mintlify/key_modules/models.mdx
- examples/models/mistral_model_example.py
- test/models/test_mistral_model.py
> feat: Add Mistral Small 3.2

- camel/toolkits/terminal_toolkit.py
> chore: update_teminal_toolkit to support docker environment log output

- docs/key_modules/storages.md
Fixes https://github.com/camel-ai/camel/issues/1607
> docs: add PgVectorStorage example and usage instructions to storages.md

- camel/agents/chat_agent.py
- camel/messages/func_message.py
- docs/mintlify/key_modules/models.mdx
- test/messages/test_func_message.py
Remove the 1.5 models and upfate the preview ids to the  GA models
> docs: Update models

- camel/utils/message_summarizer.py
- test/utils/test_message_summarizer.py
> enhance: Add Message Summarizer Feature PR2648

- docs/mintlify/get_started/introduction.mdx
> docs: Add OWL to ecosystem

- README.md
Added an Events section to document CAMEL community activities (issue #2655)
> docs: add Events section to README (#2655)

- camel/utils/mcp_client.py
> enhancement: support type:sse in MCP client argument

- camel/toolkits/__init__.py
- camel/toolkits/file_write_toolkit.py
- camel/toolkits/hybrid_browser_toolkit/hybrid_browser_toolkit.py
- camel/toolkits/note_taking_toolkit.py
- examples/workforce/eigent.py
- test/toolkits/test_note_taking_toolkit.py
> feat: add note taking toolkit, polish toolkit docstring and prompt

- camel/toolkits/__init__.py
- camel/toolkits/message_agent_toolkit.py
- examples/toolkits/message_agent_toolkit.py
- test/toolkits/test_message_agent_toolkit.py
> enhance: Add MessageAgentTool for agent communication PR2771

- camel/societies/workforce/workforce.py
- test/workforce/test_workforce.py
> feat: Workforce support dynamic worker adding

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/tasks/task.py
- camel/toolkits/hybrid_browser_toolkit/actions.py
- camel/toolkits/hybrid_browser_toolkit/agent.py
- camel/toolkits/hybrid_browser_toolkit/browser_session.py
- camel/toolkits/hybrid_browser_toolkit/hybrid_browser_toolkit.py
- camel/toolkits/note_taking_toolkit.py
- docs/conf.py
- docs/mintlify/reference/camel.toolkits.hybrid_browser_toolkit.browser_session.mdx
- docs/mintlify/reference/camel.toolkits.non_visual_browser_toolkit.nv_browser_session.mdx
- docs/reference/camel.toolkits.hybrid_browser_toolkit.browser_session.md
- examples/toolkits/hybrid_browser_toolkit_example.py
- examples/workforce/eigent.py
- pyproject.toml
- test/toolkits/test_hybrid_browser_toolkit.py
- test/toolkits/test_note_taking_toolkit.py
- uv.lock
> enhance: enhance: hybrid browser PR2810

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/societies/workforce/single_agent_worker.py
- camel/societies/workforce/worker.py
- camel/societies/workforce/workforce.py
- camel/toolkits/file_write_toolkit.py
- docs/conf.py
- examples/workforce/eigent.py
- pyproject.toml
- uv.lock
> enhance: file write toolkit, workforce sys

- camel/societies/workforce/single_agent_worker.py
- camel/societies/workforce/workforce.py
- camel/tasks/task.py
- examples/workforce/eigent.py
> enhacen: task_stream PR2829

- examples/debug/.traceroot-config.yaml
- pyproject.toml
- uv.lock
> feat: minor traceroot.ai updates

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/societies/workforce/prompts.py
- camel/toolkits/hybrid_browser_toolkit/hybrid_browser_toolkit.py
- docs/conf.py
- examples/workforce/eigent.py
- pyproject.toml
- uv.lock
> enhance: upodate 0711

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/agents/chat_agent.py
- camel/societies/workforce/prompts.py
- camel/societies/workforce/role_playing_worker.py
- camel/societies/workforce/worker.py
- camel/societies/workforce/workforce.py
- camel/tasks/task.py
- camel/toolkits/search_toolkit.py
- camel/utils/tool_result.py
- docs/conf.py
- examples/workforce/eigent.py
- pyproject.toml
- test/toolkits/test_search_functions.py
- uv.lock
> fix: Workforce previous task content not passed

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/societies/workforce/workforce.py
- camel/toolkits/search_toolkit.py
- docs/conf.py
- pyproject.toml
- uv.lock
> feat: search google supports image search

- camel/toolkits/human_toolkit.py
- docs/mintlify/reference/camel.toolkits.human_toolkit.mdx
- docs/reference/camel.toolkits.human_toolkit.md
- examples/workforce/eigent.py
…user
fixes #2879
Human toolkit now provides more explicit feedback when it sends a message to the user. 
> [BUG] HumanToolkit Provides More Explicit Feedback When Messaging User

- docs/mintlify/key_modules/tools.mdx
- docs/mintlify/mcp/connecting_existing_mcp_tools.mdx
> docs: fix tool section

- camel/storages/vectordb_storages/surreal.py
- pyproject.toml
- test/storages/vector_storages/test_surreal.py
- uv.lock
> enhance add surrealDB in vectorstorage PR2882

- examples/debug/README_traceroot.md
- pyproject.toml
- uv.lock
> Upgrade traceroot sdk version

- camel/toolkits/__init__.py
- camel/toolkits/markitdown_toolkit.py
- camel/toolkits/note_taking_toolkit.py
- camel/toolkits/openai_image_toolkit.py
- camel/toolkits/screenshot_toolkit.py
- docs/mintlify/reference/camel.toolkits.openai_image_toolkit.mdx
- docs/reference/camel.toolkits.markitdown_toolkit.md
- docs/reference/camel.toolkits.openai_image_toolkit.md
- examples/workforce/eigent.py
- test/toolkits/test_note_taking_toolkit.py
> feat: add screenshot toolkit, update notetaking toolkit

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/toolkits/web_deploy_toolkit.py
- docs/conf.py
- examples/workforce/eigent.py
- pyproject.toml
- test/toolkits/test_web_deploy_toolkit.py
- uv.lock
> enhance: webdeploy_toolkit PR2834

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/toolkits/note_taking_toolkit.py
- docs/conf.py
- examples/workforce/eigent.py
- pyproject.toml
- uv.lock
> release: v0.2.72a9

- camel/agents/chat_agent.py
- camel/societies/workforce/single_agent_worker.py
- camel/toolkits/__init__.py
- camel/toolkits/base.py
- camel/toolkits/screenshot_toolkit.py
- camel/toolkits/terminal_toolkit.py
- examples/toolkits/screenshot_toolkit_example.py
- examples/workforce/eigent.py
- test/storages/vector_storages/test_surreal.py
> fix: image handling in ChatAgent

- camel/societies/workforce/prompts.py
- camel/societies/workforce/single_agent_worker.py
- camel/toolkits/screenshot_toolkit.py
- camel/toolkits/terminal_toolkit.py
- examples/workforce/eigent.py
> enhance: screenshot and terminal toolkit, polish workforce prompt

- camel/toolkits/search_toolkit.py
- examples/toolkits/search_google_with_exclusion.py
Fixes #2817.
See example in `examples/toolkits/search_google_with_exclusion.py`
> feat: allow search_google toolkit to exclude specified domains 

- camel/memories/agent_memories.py
- camel/toolkits/video_analysis_toolkit.py
- camel/toolkits/video_download_toolkit.py
- docs/mintlify/reference/camel.toolkits.video_analysis_toolkit.mdx
- docs/mintlify/reference/camel.toolkits.video_download_toolkit.mdx
- docs/reference/camel.toolkits.video_analysis_toolkit.md
- docs/reference/camel.toolkits.video_download_toolkit.md
- examples/usecases/chat_with_youtube/app.py
- examples/workforce/eigent.py
- test/toolkits/test_video_analysis_toolkit.py
> chore: Video analysis toolkit arg renaming

- .github/ISSUE_TEMPLATE/bug_report.yml
- .gitignore
- camel/__init__.py
- camel/toolkits/hybrid_browser_toolkit/config_loader.py
- camel/toolkits/hybrid_browser_toolkit/hybrid_browser_toolkit.py
- camel/toolkits/hybrid_browser_toolkit/ts/src/browser-session.ts
- camel/toolkits/hybrid_browser_toolkit/ts/src/config-loader.ts
- camel/toolkits/hybrid_browser_toolkit/ts/src/types.ts
- camel/toolkits/hybrid_browser_toolkit/ws_wrapper.py
- docs/conf.py
- pyproject.toml
- uv.lock
> feat:cdp connect support

- camel/storages/vectordb_storages/surreal.py
- examples/workforce/eigent.py
> chore: minor update for surreal db

- camel/toolkits/hybrid_browser_toolkit_py/hybrid_browser_toolkit.py
- examples/toolkits/hybrid_browser_toolkit_example.py
> fix: browser_naming and fix get_som_screenshot

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/toolkits/web_deploy_toolkit.py
- docs/conf.py
- pyproject.toml
- uv.lock
> chore: Update web_deploy_toolkit.py

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/toolkits/base.py
- camel/toolkits/terminal_toolkit.py
- docs/conf.py
- pyproject.toml
- uv.lock
> feat: add terminal toolkit timeout

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/agents/chat_agent.py
- docs/conf.py
- pyproject.toml
- uv.lock
> chore: update onnxruntime version

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/societies/__init__.py
- camel/toolkits/mcp_toolkit.py
- docs/conf.py
- examples/toolkits/mcp/mcp_toolkit.py
- pyproject.toml
- uv.lock
> enhance: convert unvalided mcp schema satisfy openai requirement

- camel/types/enums.py
- docs/mintlify/key_modules/models.mdx
- examples/models/qwen_model_example.py
close https://github.com/camel-ai/camel/issues/2943
> feat:add qwen coder model

- camel/storages/key_value_storages/mem0_cloud.py
- test/storages/key_value_storages/test_mem0_cloud.py
- test/toolkits/test_file_write_toolkit.py
Memory fixed for mem0 finally working , add delete load all working now 
Some proof of success -
> mem0 api v2 update 

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/societies/workforce/prompts.py
- camel/societies/workforce/workforce.py
- camel/toolkits/slack_toolkit.py
- docs/conf.py
- pyproject.toml
- uv.lock
> chore: minor docstring and prompt update

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/toolkits/terminal_toolkit.py
- docs/conf.py
- examples/debug/eigent.py
- pyproject.toml
- uv.lock
> chore: move TerminalToolkit interactive to __init__

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- docs/conf.py
- pyproject.toml
- uv.lock
> release: light version for eigent

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- docs/conf.py
- pyproject.toml
- uv.lock
> chore: update dependency

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/societies/workforce/prompts.py
- camel/societies/workforce/workforce.py
- docs/conf.py
- examples/workforce/eigent.py
- pyproject.toml
- uv.lock
> enhance: workforce prompt

- camel/toolkits/hybrid_browser_toolkit/hybrid_browser_toolkit_ts.py
- camel/toolkits/hybrid_browser_toolkit/ts/src/browser-session.ts
- camel/toolkits/hybrid_browser_toolkit/ts/src/hybrid-browser-toolkit.ts
- camel/toolkits/hybrid_browser_toolkit/ts/src/types.ts
- camel/toolkits/hybrid_browser_toolkit/ts/websocket-server.js
- camel/toolkits/hybrid_browser_toolkit/ws_wrapper.py
- camel/toolkits/hybrid_browser_toolkit_py/actions.py
- camel/toolkits/hybrid_browser_toolkit_py/hybrid_browser_toolkit.py
- examples/toolkits/hybrid_browser_toolkit_example.py
- test/toolkits/test_hybrid_browser_toolkit.py
> fix bugs and change input of drag_drop tool to ref index

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/models/anthropic_model.py
- docs/conf.py
- examples/workforce/eigent.py
- pyproject.toml
- uv.lock
> fix: anthropic token counter

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/interpreters/e2b_interpreter.py
- camel/models/anthropic_model.py
- camel/utils/token_counting.py
- docs/conf.py
- examples/toolkits/e2b_custom_provider_example.py
- examples/workforce/eigent.py
- pyproject.toml
- test/models/test_anthropic_model.py
- test/toolkits/test_note_taking_toolkit.py
- uv.lock
> chore: pre commit error

- .env
- camel/toolkits/search_toolkit.py
- examples/toolkits/search_toolkit.py
- test/toolkits/test_search_functions.py
> feat: add metaso.cn API search

- camel/types/enums.py
- docs/key_modules/models.md
- docs/mintlify/key_modules/models.mdx
- examples/models/mistral_model_example.py
- pyproject.toml
- test/models/test_mistral_model.py
- uv.lock
Add ModelType.MISTRAL_MEDIUM_3_1 and update tests, examples, and docs.
> feat(models): Add Mistral Medium 3.1

- camel/toolkits/hybrid_browser_toolkit/hybrid_browser_toolkit_ts.py
- camel/toolkits/hybrid_browser_toolkit/ts/src/browser-session.ts
- camel/toolkits/hybrid_browser_toolkit/ts/src/config-loader.ts
- camel/toolkits/hybrid_browser_toolkit/ts/src/hybrid-browser-toolkit.ts
- camel/toolkits/hybrid_browser_toolkit/ts/src/types.ts
- camel/toolkits/hybrid_browser_toolkit/ts/websocket-server.js
- camel/toolkits/hybrid_browser_toolkit/ws_wrapper.py
> fix: type script browser cdp connection

- camel/societies/workforce/task_channel.py
- camel/societies/workforce/workforce.py
- examples/workforce/eigent.py
- test/workforce/test_workforce.py
> Optimise Task channel  

- CONTRIBUTING.md
- camel/toolkits/github_toolkit.py
- camel/toolkits/math_toolkit.py
- camel/toolkits/search_toolkit.py
- docs/mintlify/reference/camel.toolkits.github_toolkit.mdx
- docs/mintlify/reference/camel.toolkits.search_toolkit.mdx
- docs/reference/camel.toolkits.github_toolkit.md
- docs/reference/camel.toolkits.search_toolkit.md
- examples/toolkits/github_toolkit.py
- test/agents/test_chat_agent.py
- test/toolkits/test_github_toolkit.py
> chore: enhance toolkit function naming

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/models/openai_model.py
- docs/conf.py
- pyproject.toml
- uv.lock
> fix: openai model redundant api call

- camel/toolkits/__init__.py
- camel/toolkits/image_generation_toolkit.py
> enhance: Integrate Grok image PR3040

- camel/interpreters/microsandbox_interpreter.py
- camel/runtimes/daytona_runtime.py
- camel/toolkits/video_analysis_toolkit.py
- pyproject.toml
- uv.lock
> fix: microsand box integration

- test/toolkits/test_code_execution.py
> chore: update test

- camel/toolkits/wechat_official_toolkit.py
- examples/toolkits/wechat_official_toolkit.py
- test/toolkits/test_wechat_official_toolkit.py
> enhance: Integrate Wechat PR3087

- camel/environments/tic_tac_toe.py
- test/workforce/test_workforce_single_agent.py
> chore: MagicMock in test_workforce_single_agent.py

- camel/utils/context_utils.py
- test/utils/test_context_utils.py
> enhance: change system to user message for #3113

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/societies/workforce/workforce.py
- docs/conf.py
- docs/mintlify/reference/camel.toolkits.mcp_toolkit.mdx
- examples/agents/chatagent_stream.py
- pyproject.toml
- uv.lock
Problem
The CAMEL workforce system was creating duplicate task assignments due to a timing
issue where task assignment occurred before worker nodes were fully initialized. This
resulted in:
- Same tasks being assigned to multiple workers (e.g., Task 2 assigned to both
Developer Agent and Document Agent)
- All initial assignments being marked as invalid due to empty valid_worker_ids
- Retry mechanism creating duplicate assignments that were concatenated without
deduplication
Root Cause
1. Timing Issue: _find_assignee() was called immediately after workforce start,
before child workers completed initialization
2. No Readiness Check: Worker nodes start asynchronously but task assignment doesn't
wait for them to be ready
3. Missing Deduplication: When retry assignments occurred, they were …
> chore: fix one task re-assign to different agent

- camel/toolkits/origene_mcp_toolkit.py
- camel/toolkits/playwright_mcp_toolkit.py
- examples/toolkits/edgeone_pages_mcp_toolkit.py
- examples/toolkits/notion_mcp_tookit.py
- examples/toolkits/playwright_mcp_toolkit.py
> chore: fix pre-commity issue in PR 3095

- camel/agents/chat_agent.py
> enhance: add summarize function in agent using context util PR3149

- docs/mintlify/key_modules/storages.mdx
Add comprehensive documentation for SurrealDB vector storage.
> docs: Add SurrealDB to storage documentation

- camel/types/enums.py
- docs/mintlify/key_modules/models.mdx
- examples/models/mistral_model_example.py
- test/models/test_mistral_model.py
> feat(models): Add Magistral Small 1.2 & Magistral Medium 1.2 models

- .github/ISSUE_TEMPLATE/bug_report.yml
- camel/__init__.py
- camel/storages/vectordb_storages/oceanbase.py
- docs/conf.py
- pyproject.toml
- uv.lock
> chore: fix the name of `add_index` method in oceanbase.py

- camel/loaders/chunkr_reader.py
- test/loaders/test_chunkr_reader.py
> enhance: PR2998 add kwargs to ChunkrReaderConfig
